### ISSUE TITLE
ETable or tabulated-list?

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#1]
Should we use https://github.com/Fuco1/ETable or https://www.gnu.org/software/emacs/manual/html_node/elisp/Tabulated-List-Mode.html?

Here's the list of requirements:

- Mark/unmark/toggle marks items
- Sortable columns

ETable supports all of this but still needs work to be done on it. Tabulated List Mode is standard emacs, if it supports all of it it's probably a better option?

**Comment by Silex** [comment]
@marsam: I checked out tabulated-list a little bit, it looks nice! can't believe I missed it. I think I'll refactor with this instead of ETable because it is more mature, also people used to it will appreciate (e.g sorting).

I started a `tabulated-list` branch to see how easy it is to refactor.

**Comment by Silex** [comment]
Alright! I have a semi-working tabulated-list implementation. Tomorrow I'll make it work for containers.

**Comment by Silex** [comment]
@marsam: ok, it now works using tabulated-list.

I'll implement containers soon so we have something working, and then there will be heavy refactoring. I gave up on designing it "perfect" and decided to "make it work" followed by "make it good".

**Comment by marsam** [comment]
> I'll implement containers soon so we have something working, and then there will be heavy refactoring. I gave up on designing it "perfect" and decided to "make it work" followed by "make it good".

fair enough ;)
