### ISSUE TITLE
Switch to transient.el

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#102]
https://github.com/magit/transient/blob/master/docs/transient.org#modifying-existing-transients
https://github.com/magit/magit/pull/3728

**Comment by seagle0128** [comment]
Vote +1. Since `magit-popup` is deprecated, and it's easy to port to `transient`. Please!

**Comment by Silex** [comment]
Well it's "easy" but still takes a bit of time which I don't have :cry: 

Also some aspect of the migration I'm unsure of, like the default popup arguments https://github.com/Silex/docker.el/blob/master/docker-image.el#L55-L58

I'll try to work on it this weekend.

**Comment by seagle0128** [comment]
Thank you, @Silex . I understand you need time to make it. `easy` means not too difficult for you :-)

**Comment by Silex** [comment]
it's aliiiive #109

**Comment by seagle0128** [comment]
Thanks, @Silex .
