### ISSUE TITLE
How to pull new image from url

### ISSUE THREAD

**Issue by zwpaper** [Silex/docker.el#108]
This may be a question, but I can not find issues or content in readme.

I can see `Pull` in `Images` view, but I can only mark an image, and pull (update) it
When I was trying to pull a new image, I can not find an entry.

I have tried to place the cursor in empty line and then `Pull`, `no entry at this point` occurred.

Maybe an input window popup and we can fill the URL could be better?

**Comment by Silex** [comment]
Good idea! I need to think about the binding for that tho.

**Comment by Silex** [comment]
This was implemented in 117c220a9cea9890978a0d931f792f70d1c4e140
