### ISSUE TITLE
Wrong container names formatting, when ports does not specified

### ISSUE THREAD

**Issue by mprokopov** [Silex/docker.el#11]
I'm active user of nginx-proxy container https://github.com/jwilder/nginx-proxy, so I usually do not specify ports for containers. I use VIRTUAL_HOST=my.host environment variables instead.

It seems container names does not look properly in *docker-containers* buffer, when ports does not specified for container. 

My screenshot: 
https://www.dropbox.com/s/ap2ea1k5ynw9zob/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-01-06%2016.07.52.png?dl=0

**Comment by Silex** [comment]
Yeah, the current regexp for parsing the output of `docker ps` needs improvements, but it's not as trivial as it looks. That and the project of using docker-api.el instead of parsing the output of docker ps makes it that I always delay it...

**Comment by Silex** [comment]
@Yuki-Inoue: I'm making progress at `docker-api`.

I realised almost all my structs were obsolete! I can just use the raw JSON objects :-)

**Comment by Yuki-Inoue** [comment]
@Silex I still haven't figured out how you are trying to handle raw JSON objects, but glad to hear you've found out the way.  :+1:

**Comment by Silex** [comment]
I think we are close to having this issue fixed! I hope to push in the next days.

**Comment by Silex** [comment]
This should be fixed now. Reopen if needed.

**Comment by Yuki-Inoue** [comment]
👍
