### ISSUE TITLE
podman usage

### ISSUE THREAD

**Issue by MaSven** [Silex/docker.el#110]
So I found a couple of issues with my implementation after using it a little more. The output of podman is not really the same as docker with the format="json". There is also the option to use the go templates, but there are not the same as the one from docker. I will need some more work on this. By now I think it would be better to revert the podman feature or to disable it. Also, maybe it would be good to get more of the features of podman but I don't know if this package is the right place for this or there should be something like container.el. The basic features are the same but it diverges for example in not supporting docker-compose but using kubernetes for this. I think it would be great to have this in this package here as the whole container thing is progressing toward an open standard so that the docker cli is not the only implementation to build container and images. What do you think?

**Comment by Silex** [comment]
Hum, you mean you didn't really test your changes when doing your PR or is it just subtle changes?

Anyway, we have several options:
1. no podman support
1. basic podman support, like simply converting a bit of json/go templates back & forth
1. advanced podman support, where when podman is used we offer more options in the interface

I think `2` is reasonable, but we need to check how podman's go templates or json is. It sounds like we can simply write a `docker-{container|image|volume|etc}-convert-podman-to-docker-json` or something.

**Comment by MaSven** [comment]
I think I messed up my init.el and somehow tested against the docker cli and not against podman and now realized that the output from format="json" can not be converted the same way as the docker one. Totally my failure. Yes a docker-podman converter function would be the best idea.  But I would write one function in the utils for the output that can be filtered because podman already outputs normal json. Something like the docker-image-parse or docker-container-parse function. I'am really sorry that I messed up my testing and thought I got this right.  I have here an example output of the json format 

This one for container
```json

[
     {
          "ID": "1682c5715565",
          "Image": "docker.io/library/postgres:latest",
          "Command": "docker-entrypoint...",
          "Created": "3 weeks ago",
          "Ports": "",
          "Names": "some-postgres",
          "IsInfra": false,
          "Status": "Exited (1) 3 weeks ago",
          "State": 6,
          "Pid": 0,
          "Size": null,
          "Pod": "",
          "CreatedAt": "2019-03-22T22:21:50.564182716+01:00",
          "ExitedAt": "2019-03-22T22:21:55.455194667+01:00",
          "StartedAt": "2019-03-22T22:21:51.639426422+01:00",
          "Labels": {

          },
          "PID": "",
          "Cgroup": "",
          "IPC": "",
          "MNT": "",
          "NET": "",
          "PIDNS": "",
          "User": "",
          "UTS": "",
          "Mounts": ""
     }
]
```

**Comment by Silex** [comment]
It's okay, shit happens :tm: it's a good lesson for the next time (test better).

How I do it is I start `emacs -Q`, I navigate to the docker file using `dired`, then I load (`L` key) all the `.el` files.

I also `edebug` sometimes to make sure I'm in my modified functions.

About the json, it looks very similar, so translation functions should be easy to write.

**Comment by Silex** [comment]
Hum, I won't have time to work on supporting podman, I have plenty of work already :wink: 

I reverted the commit and pushed a `podman` branch with your changes, that way if somebody has time to work on it he can start somewhere.
