### ISSUE TITLE
Allow custom docker-compose command

### ISSUE THREAD

**Issue by jtmoulia** [Silex/docker.el#113]
In the spirit of #52 I'd love to be able to customize the `docker-compose` command.

I've written a script which wraps `docker-compose`, sending the arguments right along to the `docker-compose` command. So if I can just plug in my custom `docker-compose` command I can take advantage of my existing workflows.

If this is something that might be accepted as a PR I'm happy to implement (should be easy, right?)

**Comment by Silex** [comment]
Hello, sorry I was on holidays.

Yes good idea, just make a `docker-compose-command` variable or something.
