### ISSUE TITLE
Feature request: Allow command to not *select* anything

### ISSUE THREAD

**Issue by chrislong** [Silex/docker.el#116]
I often want to operate on a single container. Then I want to operate on a different container. Currently, I have to remember to deselect in between because any operating selects the container. This is not how any of my other tools in emacs operate on individual items (e.g., magit, dired) and I find it really annoying. I don't mind keeping the current behavior as the default but I would really, really like an option to disable the automatic selection.

**Comment by Silex** [comment]
`U` unselects everything. Is that ok for you?

**Comment by chrislong** [comment]
I don't use `ibuffer`, but for `dired`, if you're only operating on one file, you don't need to use selection (aka marks) at all (although you can also mark things and then later operate on them). Delete is kind of weird because if it succeeds it doesn't matter if the file had gotten marked/selected/whatever-term-you-want because it's not there any more. For other operations in dired (e.g., rename `R`, copy `C`, chmod `M`, shell command `!`), it just does the operation you picked on the file the cursor is on and that's it. Nothing is marked/selected or unmarked/unselected. `magit`, `find-dired`, and `locate` work the same way. I really like docker.el, but it really bugs me that it doesn't work this way, too.

**Comment by Silex** [comment]
Hum, actually you are right... `ibuffer` selects the buffer under the cursor, but dired just mention which file it will operate on.

I need to think about it, in the meantime you can press `U` to unselect everything :wink:

**Comment by Silex** [comment]
Okay, I'll move toward your suggestion with my transient refactor. Will keep you informed.

**Comment by Silex** [comment]
Will be fixed by #109.
