### ISSUE TITLE
Run commands directly

### ISSUE THREAD

**Issue by nashamri** [Silex/docker.el#12]
Hello! Thanks for this great package :+1: 

I'm trying to run some commands from elisp directly. I looked into `docker-images-run-selection` and it relies on `docker-images-selection` function to get the selected images. How can I select an image and run a given command using elisp?

I'm not sure if my question defeats the whole purpose of this package and I should run the command using `async-shell-command` :smile:

**Comment by Silex** [comment]
@nashamri: hello! sorry it seems that I completely missed this issue.

I'm not sure I understand your problem correctly, you want to run docker-images, mark some images and then run some elisp that uses the images names?

Would something like this be ok?:

``` elisp
(--each (docker-images-selection)
      (message "foo %s" it))
```

**Comment by Silex** [comment]
@nashamri: ping

**Comment by nashamri** [comment]
Oh sorry @Silex :smile: 
Thanks for getting back to this. Yes I think the solution you provided will do. :+1:
