### ISSUE TITLE
Feature request: use different face depending on the status of the container

### ISSUE THREAD

**Issue by yyoncho** [Silex/docker.el#120]
First thanks for the package!

IMO having this feature will improve the usability of the package.

**Comment by Silex** [comment]
That's a good idea. No time yet but keeping the issue open so hopefully I get to try impleneting it soon.

**Comment by Silex** [comment]
@yyoncho: I have something working at https://github.com/Silex/docker.el/tree/pretty-status

Do you see other colors than "Up / Exited / Created" for the containers status? Other areas where colors would make sense? The only thing I can think of is docker machine statuses, but not much else makes sense.

**Comment by yyoncho** [comment]
> Do you see other colors than "Up / Exited / Created" for the containers status? 

No.

**Comment by Silex** [comment]
Implemented on master :tada:
