### ISSUE TITLE
Symbol’s value as variable is void: docker-container-attach

### ISSUE THREAD

**Issue by shackra** [Silex/docker.el#124]
Recently updated this package using straight.el and turns out I catch an error:

```
Error (use-package): docker/:catch: Symbol’s value as variable is void: docker-container-attach
```

**Comment by shackra** [comment]
the commit I have registered for the package is 5027a3d541b1dcbb2f7ec0bac04a30dceeca7ce8

**Comment by Silex** [comment]
@shackra: you can update again? Also, can you show me your straight config?

**Comment by shackra** [comment]
I have updated and it seems the package points to commit 117c220a9cea9890978a0d931f792f70d1c4e140

Also, I don't experience this issue anymore
