### ISSUE TITLE
Sorting images on size is buggy

### ISSUE THREAD

**Issue by gitonthescene** [Silex/docker.el#128]
Hi there,

First thanks for the package.  Works like a treat!  I don't know if it's only my version of docker or not, but when I view images and try to sort by size the number of images in the result changes. I'm not precisely sure how this works, but it seems to be due to the fact that images of size in the kilobytes are displayed as "kB" and not "KB".  The following change seems to fix it.

    diff --git a/docker-utils.el b/docker-utils.el
    index 35cb568..9a7a3c7 100644
    --- a/docker-utils.el
    +++ b/docker-utils.el
    @@ -133,7 +133,7 @@ Execute BODY in a buffer named with the help of NAME."
     
     (defun docker-utils-unit-multiplier (str)
       "Return the correct multiplier for STR."
    -  (expt 1024 (-elem-index str '("B" "KB" "MB" "GB" "TB" "PB" "EB"))))
    +  (expt 1024 (-elem-index (upcase str) '("B" "KB" "MB" "GB" "TB" "PB" "EB"))))
     
     (defun docker-utils-human-size-to-bytes (str)
       "Parse STR and return size in bytes."

Should I submit a pull request?

Thanks,
-Doug

**Comment by gitonthescene** [comment]
FWIW, I think the behavior would be characterized as "unpredictable" because this is causing the sort predicate to fail.

**Comment by Silex** [comment]
Thanks! If you want to make a PR you can do it otherwise just let me know and I'll commit your suggestion myself given it's so simple.

**Comment by gitonthescene** [comment]
Done.  It's pull request  #129

**Comment by gitonthescene** [comment]
Thanks for getting back so quickly!

**Comment by gitonthescene** [comment]
On a separate note, it would be nice to have a configurable list of common docker commands, say starting up containers with your favorite images, which are more easily accessible.  Does this exist already?  If not, I might take a shot at adding it.

**Comment by Silex** [comment]
I think this can already be done with https://magit.vc/manual/transient/Modifying-Existing-Transients.html, and there are more examples here https://github.com/magit/magit/wiki/Converting-popup-modifications-to-transient-modifications (check "Adding a switch/option" sections).

Closing this issue as it's resolved, but you can continue asking questions. If you get something working with transient modifications and it's relevant for other users we could make a wiki article out of it.

**Comment by Silex** [comment]
Oh btw, what I meant above is adding options or actions to the image run popup, with your favorite parameters, for example https://github.com/Silex/docker.el/blob/master/docker-image.el#L159

**Comment by gitonthescene** [comment]
Thanks very much.  I'm still wrapping my head around transient and how I think I'd like it to work.  It's very convenient for poking around options but not so easy to wrap your head around quickly.  I think I'd like to see something like a Ctrl-R history in the shell though I get that that's quite different from what transient offers.  Ideally we could meld the two somehow.

Also, some options are allowed to be repeated.  Currently I get around that by adding the repeated option as the "value" of the first option.

In any event, would you consider accepting the following in the short term?

    diff --git a/docker-image.el b/docker-image.el
    index 982afca..2771af5 100644
    --- a/docker-image.el
    +++ b/docker-image.el
    @@ -172,6 +172,7 @@ and FLIP is a boolean to specify the sort order."
        ("-t" "TTY" "-t")
        ("-u" "user" "-u " read-string)
        ("-v" "volume" "-v " read-string)
    +   ("--mount" "mount" "--mount=" read-string)
        ("-w" "workdir" "-w " read-string)]
       [:description docker-utils-generic-actions-heading
        ("R" "Run" docker-image-run-selection)])

**Comment by Silex** [comment]
Sure, feel free to make a PR for any options/switches that are missing.
