### ISSUE TITLE
"No containers selected"

### ISSUE THREAD

**Issue by kedare** [Silex/docker.el#13]
Hello,

Maybe I'm doing it wrong but everytime I try to run a command I get "No containers selected", but how am I supposed to "select" a container ? I suppose my pointer on the buffer just have to be on the line of the container I want to run the action on ?

Thanks.

**Comment by kedare** [comment]
Okay, my fault, I just seen on the README that I have to "mark" the container to select it :)

**Comment by Silex** [comment]
;)

I really need to work on improving the interface, I have many ideas

**Comment by kedare** [comment]
Maybe for this, adding a feedback when trying to run a command without anything selected, as many plugins use for example helm where the simplest way to "select" an element of the list if just to have the cursor on it

**Comment by Silex** [comment]
Yeah, I intend to follow `dired` UI, when there's no element selected it automatically selects the one under the cursor

**Comment by dougm** [comment]
I borrowed some of your code and made a similar change: https://github.com/vmware/govmomi/blob/master/govc/emacs/govc.el#L94
And a minor enhancement to use dired-marker-char.  I think it'd be great to have a standalone tabulated-list-ext package at some point that our packages and others can easily share.

**Comment by Silex** [comment]
@dougm: good idea. I created https://github.com/Silex/tabulated-list-ext and added your as a collaborator, I'll make a melpa PR soonish

**Comment by Silex** [comment]
@dougm: It was merged to MELPA and I incorporated your `dired-marker-char` changes, you can start to use https://github.com/Silex/tabulated-list-extensions :-)

**Comment by Silex** [comment]
For an example on how I did it for docker.el: https://github.com/Silex/docker.el/commit/a9574de33d213d0b410784b48cfd027c108dee6d

**Comment by dougm** [comment]
@Silex thanks, very nice!  I will check it out soon.

**Comment by Silex** [comment]
@dougm: today I just found out https://github.com/politza/tablist

Don't let the crude README discourage you, it's basically tabulated-list on steroids. Check out the source, mark/unmark/filters etc... I'll probably delete tabulated-list-extensions and make some PR for tablist instead.
