### ISSUE TITLE
Using Dockerfile-mode for building via TRAMP fails

### ISSUE THREAD

**Issue by CDitzel** [Silex/docker.el#131]
I understand that opening docker-mode in a TRAMP buffer, be it a file buffer, or e.g. a Dired buffer, displays the images or running containers on the respective remote machine. However, trying now to build an image after opening a Dockerfile and hitting C-c C-b fails with 

> -*- mode: compilation; default-directory: "/ssh:me@myip#7678:/home/me/environment/" -*-
> Compilation started at Sun Apr 19 14:24:03
> 
> docker build  --tag test   -f /ssh\:me\@myip\#7678\:/home/me/environment/Dockerfile /ssh\:me\@myip#7678\:/home/me/environment/
> unable to prepare context: path "/ssh:me@myip#7678:/home/me/environment/" not found
> 
> Compilation exited abnormally with code 1 at Sun Apr 19 14:24:04

any idea how to fix that?

I know that this is more related to the other repo for dockerfile mode but in an issue on here that I saw earlier it was clearly mentioned to use dockerfile-mode to build images with Emacs.

**Comment by Silex** [comment]
Well this is an issue for https://github.com/spotify/dockerfile-mode/issues/55, as you yourself noticed. Will try to help there.
