### ISSUE TITLE
Docker Logs from a container while using a host with --tls doesn't work

### ISSUE THREAD

**Issue by maaroen** [Silex/docker.el#135]
When I request docker containers using -H xxx.xxx.com:443 --tls it shows the containers correctly, but when I try to enter the logs of a container with L it shows an error message: 

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/xxx.adapter.api/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

This while if I press I for inspect, it works as expected.

**Comment by Silex** [comment]
Hum, I never use `-H` so please help me here.

I don't understand how you get the `--tls` flag given the current transient does not offer that option.

Also inspect is so similar to logs that I don't understand how one works while the other not.

Can you reproduce the problem and then copy the relevant lines from `C-h e`? You'd be able to see what docker commands are produced, copy the ones from log and the ones from inspect, also maybe test them in a terminal to figure out what is happening.

**Comment by maaroen** [comment]
I got the --tls flag, just by putting it behind the given host after using the -H flag

If I see this:
docker --host platform-docker-test.xxx.com:443 --tls container inspect adapter.api

docker --host platform-docker-test.xxx.com:443 --tls container ls --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .CreatedAt}},{{json .Status}},{{json .Ports}},{{json .Names}}]"

docker container logs adapter.api: exited abnormally with code 1.

Then it looks like it is trying to open the logs, but it doesn't use the --host tags.

Can is be that this is forgotten?

**Comment by Silex** [comment]
> I got the --tls flag, just by putting it behind the given host after using the -H flag

Nice trick. I'll add `--tls` to the option.

Thanks for the debugging, yes it looks like it was forgotten, tho I don't understand why by reading the code. I'll investiguate.

**Comment by maaroen** [comment]
I needed it and I figured that was a way to get it behind.

Glad I could help you, good luck finding the issue! I'll wait for a fix.

**Comment by Silex** [comment]
Found the issue, fix incoming.

**Comment by maaroen** [comment]
> Found the issue, fix incoming.

Nice, thanks for the fast action!

**Comment by Silex** [comment]
Fix on master. For the `--tls` flag, I think I'll add all the TLS options but hide all options in transient, because they are not used most of the time, like there is in magit.

**Comment by Silex** [comment]
@maaroen: check https://github.com/Silex/docker.el/commit/a145c5673dfcee256f600f43d862a8603faf500a and tell me if that works for you.

**Comment by maaroen** [comment]
@Silex I had to figure out how to use the transient, but by doing C-x l, I was able to set the transient level for -H en -Tt to 1, and it works now.
The logs work as well, thanks a lot for fixing this!
