### ISSUE TITLE
Support for  additional log options

### ISSUE THREAD

**Issue by maaroen** [Silex/docker.el#138]
Hello @Silex,

Is is possible to add additional options to the container log commands? for example:
--tail
--since
--until
This are the available options: https://docs.docker.com/engine/reference/commandline/logs/

With kind regards,

Maaroen

**Comment by Silex** [comment]
Added in d6233bdb9ccaee4da7cdc0ef162bfe4727227142

**Comment by maaroen** [comment]
@Silex Thanks for the fast answers once again, maybe it's an idea to add:
--details
--timestamps (-t)
to be complete according to the docker documentation?
I realise it was better if I put them in my first post.

**Comment by Silex** [comment]
I don't like the idea of "being complete" just for the sake of being complete.

I mean, eventually, sure... but everything you add needs maintainance, etc. There is already so many areas that need completion... see #118 and #6, the scope is huge.

I much prefer to add things that people use for now. Do you agree?

**Comment by maaroen** [comment]
Yea you do have a point here, I do agree.
I'll let you know if there are more features that i'm missing!
thanks
