### ISSUE TITLE
Container refresh from container overview

### ISSUE THREAD

**Issue by maaroen** [Silex/docker.el#139]
Hello @Silex,

Do you think it is possible to add a shortcut to the container overview to refresh the container list?
I could use this for example to check a container status after restarting, without having to reopen the whole command and enter the host string again.

You could for example put it on g r, which I think is more commonly being used for refreshes.

With kind regards,

Maaroen

**Comment by Silex** [comment]
It's already on `g` in vanilla emacs and on `g r` with evil-collection. Or are you talking about something else?

**Comment by maaroen** [comment]
Oh strange, I tried g r yesterday but it didn't work, I guess I messed something up. It works now as intended, sorry for the inconvenience!
