### ISSUE TITLE
Show error messages from docker daemon

### ISSUE THREAD

**Issue by maaroen** [Silex/docker.el#140]
Hello @Silex,

I just tried to start a container, but it didn't want to start from the interface, in the logs I saw nothing either.
But when I tried to start the container from a normal commandline, I received this error message:
![image](https://user-images.githubusercontent.com/22098498/84150265-e9d7b900-aa61-11ea-874c-b9e15c551544.png)

Is is possibile to show these error messages somewhere so it is clear why a container doesn't want to start?

With kind regards.

Maaroen

**Comment by Silex** [comment]
Does the message appear in `C-h e` ?

But yeah, basically I need to work on #4 which would allow to show these errors.

I'm currently working on something else tho, so if you want to help help me figure out how to reuse magit-process.

**Comment by maaroen** [comment]
The message sadly doesn't appear in C-h e.

Ah, no hurries ofcourse. I'm just posting here what I find to have it listed.

I'm not very familiar with elisp yet sadly, I just recently started using emacs (with evil). I want to try to find more time to get more into it. I would like to help, do you perhaps have something that I could get a nice start from to get into it?

**Comment by Silex** [comment]
I think this should be fixed, reopen if not.
