### ISSUE TITLE
Error while installing from MELPA

### ISSUE THREAD

**Issue by mihaiolteanu** [Silex/docker.el#143]
When trying to install docker.el from MELPA, I get lots of "reference to free variable x" and "the function y is not known to be defined". Eventually, the `byte-compile-file` errors with

```
Compiling file /home/mihai/.emacs.d/elpa/docker-20200610.715/docker.el
at Mon Jun 22 13:18:00 2020
docker.el:32:1:Error: Symbol’s value as variable is void: docker-compose-build
```

Just a small printscreen (the compile log is over 200 lines long):
![screenshot1592821333](https://user-images.githubusercontent.com/8273519/85279944-ea277980-b48f-11ea-954b-bd653569fe0b.png)

**Comment by mihaiolteanu** [comment]
Solved.

My version of `transient` did not have the `transient-define-prefix`.
I can clearly see in your Package Requires that you specify `transient "0.2.0"`, but I've had one from 2019 in my local packages, presumably version 0.1.0.

I've had to manually install the version 0.2.0 from melpa. The errors and warnings are now gone.

**Comment by Silex** [comment]
Ha, I started to reply to this saying that by me everything worked in an "emacs -Q" environment, but apparently I never got to hit enter.

Sorry for that, and glad you worked it out yourself :wink:
