### ISSUE TITLE
Not working in Doom Emacs

### ISSUE THREAD

**Issue by NickRaleigh** [Silex/docker.el#144]
Hi, 
Emacs noob here. I just installed docker.el in Doom Emacs, and every command invoked from M-x results in a similar error:

 ![image](https://user-images.githubusercontent.com/23318932/87360911-4f6b0980-c528-11ea-81b1-0acbbee26c40.png)

**Comment by shukryzablah** [comment]
Did you try uncommenting docker in init.el or setting it up in addition to that?

**Comment by NickRaleigh** [comment]
Yes, I uncommented docker from init.el:

![image](https://user-images.githubusercontent.com/23318932/87572931-7856e000-c689-11ea-958c-1a2084703d73.png)
