### ISSUE TITLE
Add support for `docker stats`

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker.el#150]
Reopening [issue 50 from docker-emacs](https://github.com/Silex/docker-emacs/issues/50). I'd like to add support for `docker stats`.

This command on its own already opens a stream that auto-updates – this would be the simplest integration but it would mean that we had to run a `ansi-shell` to display it and we wouldn't be able to sort, as we currently are in other commands (e.g. `docker images ls`).

Another possibility is to use the `--no-stream` argument and call it every X seconds, then following a logic similar to `docker-image.el`.

What do you think about this?

**Comment by antoineB** [comment]
Directly hit the API (https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats) for better integration in emacs.

There is https://github.com/Silex/docker-api.el by the same author I don't know why he decided to use the `docker` cmd line instead.
