### ISSUE TITLE
`docker-volume-dired` errors when opening docker volume

### ISSUE THREAD

**Issue by egh** [Silex/docker.el#157]
emacs: 28.0.50-master-30d974b installed via [snap](https://snapcraft.io/emacs)
os: ubuntu 20.04

Steps to reproduce:

1. `M-x docker`, `v`
2. Select volume and type `d` to open dired

Result: Error
```
ls-lisp--insert-directory: Reading directory: No such file or directory, /sudo::/var/lib/docker/volumes/sitecontent-authoring_artifacts/_data
```

Cause: there is a newline at the end of the string.

Fix, which seems to work for me, is to add `s-trim-r` to `docker-run-docker`:

```
(defun docker-run-docker (&rest args)
  "Execute \"`docker-command' ARGS\" and return the results."
  (docker-with-sudo
    (let* ((flat-args (-remove 's-blank? (-flatten (list (docker-arguments) args))))
           (command (s-join " " (-insert-at 0 docker-command flat-args))))
      (message command)
      (s-trim-right (docker-shell-command-to-string command)))))
``

**Comment by egh** [comment]
Forgot to add, this package is amazing!!! It makes using docker so much more intuitive for me.

**Comment by Silex** [comment]
Thanks for the report, weird that it wasn't caught before. You want to make a PR or shall I just fix it myself?

**Comment by egh** [comment]
Thanks! I'll file a PR later today.
