### ISSUE TITLE
Select the current line if no selection

### ISSUE THREAD

**Issue by Yuki-Inoue** [Silex/docker.el#16]
As discussed in https://github.com/Silex/docker.el/issues/13 , its nice to select the current element in the list if nothing is selected.

**Comment by Silex** [comment]
Yes, I need to work on it as soon as I have some time available.

That and have all the commands run in the background, like in magit.

**Comment by Silex** [comment]
I have something semi-working! Will push it soon :)

**Comment by Yuki-Inoue** [comment]
Glad to hear that! :)

**Comment by Silex** [comment]
By the way, if you update tabulated-list-extensions, the selected rows should highlight.

**Comment by Yuki-Inoue** [comment]
I'll check. Thanks for notification!

**Comment by Silex** [comment]
@Yuki-Inoue: it's pushed! if you could serve as beta tester on this feature it'd be great :wink: 

Make sure you also have the latest version of https://github.com/Silex/tabulated-list-extensions

**Comment by Silex** [comment]
Reopen if still an issue ;)

**Comment by Yuki-Inoue** [comment]
I've confirmed docker.el working as I issued in this thread. Thanks!

**Comment by Silex** [comment]
:+1:
