### ISSUE TITLE
Make 1.4.0 release

### ISSUE THREAD

**Issue by abcdw** [Silex/docker.el#164]
There are no new tags for quite some time. Can you release a new version, please?

It will make easier for downstream package managers and distributions update docker.el package in their repositories.

Thank you for all your work!)

**Comment by Silex** [comment]
Good idea. It's done :rocket:

**Comment by abcdw** [comment]
On 2021-09-14 07:34, Philippe Vaucher wrote:

> Good idea. It's done :rocket: 

Thank you.  Updated package for GNU Guix:

https://issues.guix.gnu.org/50598
