### ISSUE TITLE
/bin/sh docker command not found

### ISSUE THREAD

**Issue by bernaloo** [Silex/docker.el#176]
Im missing something trivial here. 

running emacs and docker in a mac os x Catalina

I get the following kind of error, when executing any of the docker.el binded commands. 

I have checked, that "docker" is reachable from /bin/sh and globally, yet docker.el does not seem to find it. 

`docker container ls --filter status=running --format="[{{ json .Names }},{{json .ID}},{{json .Image}},{{json .Command}},{{json .CreatedAt}},{{json .Status}},{{json .Ports}},{{json .Names}}]"
transient-setup: Could not read following string as json:
/bin/sh: docker: command not found
Mark saved where search started [2 times]
`

thanks

**Comment by Silex** [comment]
Your emacs does not have the right PATH.

Try something like https://github.com/purcell/exec-path-from-shell, to make sure it works you can `M-x shell` then `echo $PATH` to confirm it's the same PATH as in a terminal from which docker works.

**Comment by bernaloo** [comment]
That was the solution. Thanks
