### ISSUE TITLE
Performance issues after docker-status introduction

### ISSUE THREAD

**Issue by noorul** [Silex/docker.el#177]
With the changes in https://github.com/Silex/docker.el/pull/84, I see that there is significant lag testing my patience. Please provide a mechanism to disable this.

**Comment by Silex** [comment]
@joshbax189 any idea how to implement this?

**Comment by joshbax189** [comment]
@Silex yeah should be greatly improved by #171

**Comment by noorul** [comment]
If anyone else is facing this issue, as a temporary mechanism I added the following to my config
`
(defun docker-container-description-with-stats() "Containers")
(defun docker-image-description-with-stats() "Images")
(defun docker-network-description-with-stats() "Networks")
(defun docker-volume-description-with-stats() "Volumes")
`

**Comment by Silex** [comment]
@noorul I'm working on the async branch which should dramatically improve performances. I'm also thinking about a global flag to disable stats.

**Comment by Silex** [comment]
@noorul, @joshbax189 can you guys give the [`async`](https://github.com/Silex/docker.el/tree/async) branch a test?

I need to handle things like error handling but it'd be functionnal.

Then I'll work on the magit-section (`$` buffer) and the `vterm` support.

**Comment by Silex** [comment]
@noorul: check the latest version and tell me if that's ok or reopen if you still need a mechanism to disable the status.

**Comment by noorul** [comment]
This looks good to me with respect to performance. One issue is that the too many messages are being dumped to message buffer (bottom of the screen). This is distracting.

**Comment by noorul** [comment]
Maybe a dedicated buffer like *magit-process* buffer could be better.

**Comment by Silex** [comment]
This is the plan, yes.
