### ISSUE TITLE
Help with start-process

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#178]
Hello,

I'm going nuts, can someone explain:

``` shell
silex@silex-laptop:~/docker.el$ docker network ls --format="[{{ json .ID }},{{json .ID}},{{json .Name}},{{json .Driver}},{{json .Scope}}]"
["37a5ee2e66ca","37a5ee2e66ca","bridge","bridge","local"]
["28c47901bbef","28c47901bbef","host","host","local"]
["27167d55864f","27167d55864f","none","null","local"]

silex@silex-laptop:~/docker.el$ ls -alh
total 148K
drwxr-xr-x  4 silex silex 4.0K fév  4 00:43 .
drwxr-xr-x 23 silex silex 4.0K mai 31  2020 ..
-rw-rw-r--  1 silex silex 3.6K jan 29 10:47 CHANGELOG.md
-rw-rw-r--  1 silex silex  13K jan 31 22:00 docker-compose.el
```

As you see, nothing is quoted weirly or anything.

Now if I do the same in emacs:

``` elisp
(start-process "test" "test" "docker" "network" "ls" "--format=\"[{{ json .ID }},{{json .ID}},{{json .Name}},{{json .Driver}},{{json .Scope}}]\"")
(start-process "test2" "test2" "ls" "-alh"))
```

Here is the output in `test`:

```
"["37a5ee2e66ca","37a5ee2e66ca","bridge","bridge","local"]"
"["28c47901bbef","28c47901bbef","host","host","local"]"
"["27167d55864f","27167d55864f","none","null","local"]"

Process test finished
```

Here is the output in `test2`:

```
total 148K
drwxr-xr-x  4 silex silex 4.0K fév  4 00:47 .
drwxr-xr-x 23 silex silex 4.0K mai 31  2020 ..
-rw-rw-r--  1 silex silex 3.6K jan 29 10:47 CHANGELOG.md
-rw-rw-r--  1 silex silex  13K jan 31 22:00 docker-compose.el

Process test2 finished
```

Why is there extra quotes around the docker output? :exploding_head: 

I tried playing with `process-connection-type` but the quotes are always there. Using a filter does not change anything, the text I receive is extra quoted :disappointed: 

@tarsius, @purcell: I figure you guys know why this happens :sweat_smile:

**Comment by Silex** [comment]
Apparently emacs *doesn't* process quotes the same way as the shell does, so `"--format=\"[{{ json .ID }},{{json .ID}},{{json .Name}},{{json .Driver}},{{json .Scope}}]\""` is actually interpreted like `--format='"[{{ json .ID }},{{json .ID}},{{json .Name}},{{json .Driver}},{{json .Scope}}]"'`

**Comment by purcell** [comment]
Yup, in your original command the `"` is intercepted by the shell, and results in the argument `--format=[{{ json .ID }},{{json .ID}},{{json .Name}},{{json .Driver}},{{json .Scope}}]` passed to the executable itself. It's really just a way to stop the shell from breaking the command on spaces. You could just as easily use `"--format=...."`. In Emacs, `start-process` takes multiple args, and each is passed unchanged as a distinct arg to the process, so any quotes will find their way into the argument itself.
