### ISSUE TITLE
vterm support

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#179]
I think it means that only `docker attach/logs/run` would be feasible.

E.g I don't see a way to open a vterm shell inside an existing container, given it all works with TRAMP.

**Comment by noorul** [comment]
I could think of `docker-compose-exec`, `docker run` from image list and also we could provide exec option in `docker image list`

**Comment by Silex** [comment]
Ah, apparently vterm works over TRAMP! When inside a docker container with TRAMP I was able to start a vterm buffer.

**Comment by Silex** [comment]
So we can use vterm everywhere, the question is that we probably want to do like projectile and offer a shell/eshell/vterm experience... I'll think about it.

**Comment by Silex** [comment]
It's on master! Please give me feedback.

**Comment by noorul** [comment]
@Silex Awesome! I will give it a try.
