### ISSUE TITLE
docker rmi  with force switch doesn't work

### ISSUE THREAD

**Issue by novakboskov** [Silex/docker.el#18]
`docker rmi hello-world:latest -f` which is produced by `D -f D` in `docker-images` results in error:
```
Failed to remove image (hello-world:latest): Error response from daemon: conflict: unable to remove repository reference "hello-world:latest" (must force) - container f6fb337fbe2e is using its referenced image 690ed74de00f
Failed to remove image (-f): Error response from daemon: No such image: -f:latest
```

Should not rmi with force switch produce something like ` docker rmi -f hello-world:latest`? I'm really new to Docker, so excuse me if I'm wrong.

**Comment by Silex** [comment]
Hello!

Looks like you found a bug. I'll look into it.

**Comment by Silex** [comment]
Reopen if still present :wine_glass:
