### ISSUE TITLE
Please don't rewrite history on master

### ISSUE THREAD

**Issue by chasecaleb** [Silex/docker.el#181]
Hi,

At some point within the past week or so it looks like you rewrote history on master, which broke my emacs.d since I use your library as a git submodule. I had it pinned to commit 8d64cf4f84d7da5f839a8248fdddfb635a63f803 but it looks like the equivalent commit is now ff8a564622df8cf086e4ace9eb4251a74b20f77b, since the most recent three commits were rewritten. The [golden rule of rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#the-golden-rule-of-rebasing) is to never do it on public branches.

It's your repo of course so feel free to ignore me, but I wanted to point this out in case you weren't aware of the ramifications.

P.S. Thanks for writing this mode, it's great!

**Comment by Silex** [comment]
Ah, thanks for notifying I never thought of this case.

I often rewrite public history given I'm (almost) the only one pushing.

I'll try to avoid it in the future.

**Comment by chasecaleb** [comment]
Thanks for the consideration! And I completely get what you mean, I rebase religiously too for the same reasons :+1:
