### ISSUE TITLE
vterm-mode is used in `log` output buffer also

### ISSUE THREAD

**Issue by noorul** [Silex/docker.el#188]
After adding support for vterm, all the other buffers are inheriting `vterm-mode` and hence key bindings. I think we should only use vterm for only terminal interaction and all other buffers should use the old way.

**Comment by Silex** [comment]
Using `vterm` for everything is much better because the experience is always the same, output is properly parsed instead of all the ugly display earlier with `shell-mode`, etc.

Why is this a problem that you have vterm keybindings?

**Comment by Silex** [comment]
@noorul: ping

**Comment by noorul** [comment]
It is not perfect, for sometimes the buffer gets clipped when we adjust the window.

**Comment by Walheimat** [comment]
And yes, the buffer content gets clipped and makes longer log lines unreadable.

**Comment by Silex** [comment]
Okay, for the time being replace https://github.com/Silex/docker.el/blob/master/docker-process.el#L65 by `(if nil`

**Comment by noorul** [comment]
IMO we should have a separate mode for log buffers.

**Comment by Silex** [comment]
Ok guys, please update and use `(setq docker-run-async-with-buffer-function 'docker-run-async-with-buffer-shell)`
