### ISSUE TITLE
Fix CI builds on MELPA stable

### ISSUE THREAD

**Issue by LaurenceWarne** [Silex/docker.el#193]
Currently CI builds which grab deps from MELPA stable are failing (example:  https://github.com/Silex/docker.el/actions/runs/1941613092), this is because we're using `transient-default-value` which was added after the most recent `transient` release.

Ping @Silex, though I think I'm on the watch list for `transient` releases anyway so I can probably PR a quickfix on release.

**Comment by Silex** [comment]
Ah, you meant an issue _here_ :laughing: 

I thought you meant an issue on transient. I'll create one.

**Comment by Silex** [comment]
Well asking for a new release stresses tarsius too much, so I'll remove MELPA stable tests.
