### ISSUE TITLE
Empty lists of images and containers

### ISSUE THREAD

**Issue by zeeros** [Silex/docker.el#195]
I have this problem with both melpa and melpa-stable versions. Containers and images are not displayed.

![image](https://user-images.githubusercontent.com/1713464/158990861-06c5d917-aafe-4ed1-a037-b8261634e2cc.png)

Also, if I try to pull a new image nothing happens.

**Comment by Silex** [comment]
Can you show me what is displayed in the `* Messages *` buffer (`C-h e`) when you try to display the images list?

**Comment by zeeros** [comment]
Nothing is printed out in `*Messages*`

**Comment by Silex** [comment]
What is your emacs version? Can you try with `emacs -Q`?

**Comment by zeeros** [comment]
Emacs 27.2

![image](https://user-images.githubusercontent.com/1713464/159178004-07fe61ca-5b95-4db9-95c1-9dda3a03bba3.png)

**Comment by Silex** [comment]
This is really weird.

What does happen when you do: `M-x eval-expression RET (aio-wait-for (docker-image-entries)) RET` ?

**Comment by zeeros** [comment]
`Symbol’s function definition is void: transient-default-value`

**Comment by Silex** [comment]
Seems like you get hit by https://github.com/magit/transient/issues/190

But that does only happen with MELPA-stable, and you said you also tested with unstable.

Can you try with unstable again and make sure `transient` uses unstable?

**Comment by zeeros** [comment]
With `transient-20220314.1605` both images and containers are correctly displayed

**Comment by theottm** [comment]
Encountered the same problem. Also nothing in `*Messages*`. Maybe it would be nice to catch this error ?
For people using `use-package` and `straight` you can use this to get the latest version of transient:
```elisp
(use-package transient
  :straight '(transient
              :type git
              :host github
              :repo "magit/transient"
              :commit "2e4426fe8161893382f09b3f4635e152ee02488e"
              ))
```
Of course replace commit with [appropriate commit hash](https://github.com/magit/transient/commits/master).

**Comment by Silex** [comment]
I don't see how it's even feasible to catch this error.

**Comment by sandwoodK** [comment]
Fall on same issue. It may discourage people with very few knowledge of emacs /  package  of using this.  Agree that if possible some trace at least in *Messages* should point out to something.

**Comment by Silex** [comment]
Should be fixed by https://github.com/Silex/docker.el/commit/21d0039e0dd5c9c1abc19697cf46874807ae437e, not sure why I missed this simple fix.

**Comment by Silex** [comment]
Actually no I also need to publish a tag. Ok well time for a release 😅

**Comment by Silex** [comment]
Release is done 🥳 this should not happen anymore.
