### ISSUE TITLE
Better Docker Compose support

### ISSUE THREAD

**Issue by unmonoqueteclea** [Silex/docker.el#199]
Hey, I am planning to add a new option to list all the Docker Compose projects (https://docs.docker.com/engine/reference/commandline/compose_ls/) with their status. I could add keybindings to start or stop their containers, and even a keybinding to show all the containers from a specific compose project.

Do you consider this could be approved and eventually be merged?

**Comment by Silex** [comment]
Hello,

Yes sure, would that work a bit like projectile? Or more like a tabulated list of previously used docker-compose projets with columns summarizing the running/stopped/etc containers?

**Comment by unmonoqueteclea** [comment]
My idea was doing a tabulated list of docker-compose projects.

But maybe, just offering a way to complete known projects when doing things like `docker-compose-start`or `docker-compose-stop`is fine. The problem with current `docker-compose`implementation in `docker.el` is that you need to be in the directory that contains the `docker-compose.yaml` file. I want to get rid of that limitation.
