### ISSUE TITLE
Warning in Emacs 29

### ISSUE THREAD

**Issue by seagle0128** [Silex/docker.el#209]
I got this warning in recent Emacs 29 build. It seems new package `tramp-container` is introduced.

```elisp
⛔ Warning (emacs): Package ‘docker-tramp’ has been obsoleted, please use integrated package ‘tramp-container’
```

**Comment by Silex** [comment]
Should have been fixed by #208, can you confirm?

**Comment by seagle0128** [comment]
It works for me. Thanks!

**Comment by jumper047** [comment]
Pardon my interruption, but maybe you should also bump required emacs version to 29, because now package is not working correctly with older versions?%)
