### ISSUE TITLE
Improve docker-machine

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#21]
@benswift, I'm not a user of docker-machine, can you tell me wether incorporating

https://github.com/dougm/docker.el/commit/b328f2225e275d33b43521d6ad9052ec552ffb3a#diff-34b17d4fecbd8f93346451d97efbe510R36

Is relevant? Also, can you test wether docker-machine works correctly in my merge? Would you be interested into being added as a maintainer for the docker-machine part?

Thanks :wink:

**Comment by Silex** [comment]
Also, I plan on renaming `docker-machine-ls` to `docker-machine`, it makes more sense. I'll rename all the `eieieo` structs with some `-struct` postfix or something. I'll probably add some `CONVENTIONS.md` for the coding conventions :)

**Comment by benswift** [comment]
Hi folks

Sorry about my delay in replying - been swamped with a release of
another project this week.  I'll try and have a look next week, though.

Cheers,
Ben

**Comment by benswift** [comment]
Cool, sounds good - prioritise the interactive commands over the
internal structs is a good call.

Ben

**Comment by Silex** [comment]
@benswift: I refactored quite a lot, can you tell me if docker-machine still works?
