### ISSUE TITLE
Cannot see images, containers, networks, or anything

### ISSUE THREAD

**Issue by drivs** [Silex/docker.el#211]
As you can see on the below screenshot, I'm not able to list any of the docker images I have pulled. What is happening here?

![image](https://user-images.githubusercontent.com/4217621/198586371-d946d5b3-e450-434f-a784-2a32e7953cfc.png)

**Comment by Silex** [comment]
Is your emacs shell fish as well? What does the buffer `* Messages *` says?

Otherwise as usual, OS/Emacs version etc.

**Comment by andrewsw** [comment]
I have this issue too, and would love to help if I can. Current version of the packages is 20221013.1201

* My `*Messages*` buffer is clean. 
* `M-x emacs-version` => `GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02`. 
* MacOS 12.6.1 Monterey
* `docker --version` => `Docker version 20.10.17, build 100c701`

I get a blank screen just like @drivs, despite many running containers. 

I've intermittently tried this package several times, and always it's been this way. 

My current version of the package is 20221023.1201, and here are the logs of the install from *Messages*

```
Package ‘docker-20220530.603’ deleted.
Contacting host: melpa.org:443
Parsing tar file...done
Extracting docker-20221023.1201/
Extracting docker-20221023.1201/docker-compose.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-compose.el
Extracting docker-20221023.1201/docker-container.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-container.el
Extracting docker-20221023.1201/docker-core.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-core.el
Extracting docker-20221023.1201/docker-faces.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-faces.el
Extracting docker-20221023.1201/docker-group.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-group.el
Extracting docker-20221023.1201/docker-image.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-image.el
Extracting docker-20221023.1201/docker-network.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-network.el
Extracting docker-20221023.1201/docker-pkg.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-pkg.el
Extracting docker-20221023.1201/docker-process.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-process.el
Extracting docker-20221023.1201/docker-utils.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-utils.el
Extracting docker-20221023.1201/docker-volume.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-volume.el
Extracting docker-20221023.1201/docker.el
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker.el
Generating autoloads for docker-compose.el...done
Generating autoloads for docker-container.el...done
Generating autoloads for docker-core.el...done
Generating autoloads for docker-faces.el...done
Generating autoloads for docker-group.el...done
Generating autoloads for docker-image.el...done
Generating autoloads for docker-network.el...done
Generating autoloads for docker-pkg.el...done
Generating autoloads for docker-process.el...done
Generating autoloads for docker-utils.el...done
Generating autoloads for docker-volume.el...done
Generating autoloads for docker.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-autoloads.el [2 times]
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201... [2 times]
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-compose.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-compose.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-container.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-container.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-core.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-core.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-faces.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-faces.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-group.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-group.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-image.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-image.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-network.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-network.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201... [2 times]
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-process.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-process.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-utils.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-utils.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-volume.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker-volume.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Compiling /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker.el...done
Wrote /Users/andrew/.emacs.d/elpa/docker-20221023.1201/docker.elc
Checking /Users/andrew/.emacs.d/elpa/docker-20221023.1201...
Done (Total of 11 files compiled, 2 skipped)
```

**Comment by Silex** [comment]
If you `M-x term` then type `docker ps -a` does it work?

**Comment by seandjones92** [comment]
I'm running into the same issue and installed and setup exec-path-from-shell but am still getting nothing in my docker popup. I can run docker commands from eshell, which is using the docker command provided from `docker-core.el` as seen below without issues

```
Welcome to the Emacs shell

~/Desktop $ which docker
docker is an autoloaded interactive byte-compiled Lisp function in ‘docker-core.el’.
~/Desktop $ docker ps 
CONTAINER ID   IMAGE     COMMAND       CREATED       STATUS          PORTS     NAMES
21c29978d614   python    "/bin/bash"   4 weeks ago   Up 16 minutes             saltlab
~/Desktop $

**Comment by andrewsw** [comment]
I tried `term` with bash, `ansi-term` with sh, and `eshell`. Docker works just fine. Invoking docker via `shell-command` also works just fine. 

Additionally, I hacked up `docker-run-start-file-process-shell-command` to give me some output, and it's clear that the execution of docker is working. It's just falling apart somewhere between there and the display buffer.

**Comment by Silex** [comment]
> I'm running into the same issue and installed and setup exec-path-from-shell but am still getting nothing in my docker popup. I can run docker commands from eshell, which is using the docker command provided from `docker-core.el` as seen below without issues

I think `which` lies to you, using `(docker)` would call the elisp function but "docker ps" actually calls the real docker binary.

Does not help with the issue tho, something weird is going one, probably in `aio`.

**Comment by Silex** [comment]
Ok I checked in a docker container:

![image](https://user-images.githubusercontent.com/16015/203725845-0fa1c4f4-c5d5-439e-b9fe-0e9f8f4f6711.png)

Preeeeetty sure the problem is OSX related.

**Comment by Silex** [comment]
What happens if you do `M-x eval-expression (aio-wait-for (docker-container-entries-propertized (docker-container-ls-arguments)))` ?

**Comment by Silex** [comment]
@andrewsw, @seandjones92, @drivs: friendly ping :wink:

**Comment by andrewsw** [comment]
> (aio-wait-for (docker-container-entries-propertized (docker-container-ls-arguments)))

invokes the debugger with 

`(void-function transient-default-value)`

`transient-default-value` was introduced to `transient` [about 11 months ago](https://github.com/magit/transient/blame/23b8670bfda65436fc03eb03adc8191a3e4e5a0d/lisp/transient.el#L2808), and my installation doesn't include it. 

After upgrading `transient`, this is now working for me. 

It looks to my untrained eye like the dependency specification for `transient` is just incorrect. I see `transient-0.3.7` is required, but that version predates `transient-default-value`. I don't know what the earliest required version of `transient` is, but `20221127.2227` works for me.

**Comment by flocks** [comment]
I have the same problem on linux. 

I have updated both `docker.el` and `transient.el` package with `straight-pull-all` and I require `transient.el` before `docker.el` in my config but I'm still running into the problem.

However if I manually go to the `transient-default-value` definition in the `transient` package and eval it myself, the problem is solved.

**Comment by drivs** [comment]
I got it working now, after installing the transient package. Thanks for the help!

TRAMP in Emacs 29 will have support for Docker out of the box ([Link](https://blog.phundrak.com/emacs-29-what-can-we-expect/#tramp-natively-supports-docker-podman-and-kubernetes)).

**Comment by Silex** [comment]
Oh well there's nothing I can do, tarsius does not want to do a stable release so we are stuck at 0.3.7 (https://stable.melpa.org/#/transient).

He has been noticed (https://github.com/magit/transient/issues/190) but it's not a priority for him.

**Comment by Silex** [comment]
@purcell: am I allowed to "depend" on melpa-unstable packages like "20221127.2227" ? Is there a notation to mean "the latest please" ?

**Comment by purcell** [comment]
There's no special notation for that. Ideally packages should work with stable released versions of packages, and not all users will have MELPA "unstable" enabled. But if you have no choice, e.g. because there's no stable release of the thing you're depending on, then you can depend on snapshot versions. Note that this means it's not very meaningful to have a stable release of _your_ package, because it wouldn't be usable by people who try to avoid MELPA "unstable".

**Comment by Silex** [comment]
Thanks a lot of the clarification and happy new year :smile:
