### ISSUE TITLE
Mark all images/containers on `% m RET`

### ISSUE THREAD

**Issue by pennersr** [Silex/docker.el#212]
In other parts of Emacs, Dired for example, I can type `% m RET` to mark all files. 

However, when I type `M-x docker-containers RET % m RET` I run into an error message: `No regexp given`.

Please consider altering the behavior to make the user experience consistent to that of default Emacs and select all images/containers when no regexp is given.

**Comment by pennersr** [comment]
I just had a look on the way it is implemented, and apparently this is an issue in `tablist`.

**Comment by pennersr** [comment]
Filed upstream: https://github.com/politza/tablist/issues/27

**Comment by Silex** [comment]
I use `*` to mark all, it also works in dired.

**Comment by pennersr** [comment]
@Silex Thanks for the tip. Though, it would still be good to have consistent behavior throughout Emacs and support `% m RET` as well.

**Comment by Silex** [comment]
Given this is filled upstream I'll close this. Reopen if you think it's wrong.
