### ISSUE TITLE
Can't run a shell inside container

### ISSUE THREAD

**Issue by jumper047** [Silex/docker.el#215]
I received an error when tried to run shell in container: `Method ‘docker’ is not known`.  Installation of the `docker-tramp` package fixes the issue for me, but I still considering it a bug:) - my emacs 28 don't have tramp-container.el

**Comment by Silex** [comment]
Fixed in [d837c7d](https://github.com/Silex/docker.el/commit/d837c7dfc6c5a949f19e9d673a4ac70b960d282e)
