### ISSUE TITLE
Make `docker-images` column configurable, especially for Repository column

### ISSUE THREAD

**Issue by Yuki-Inoue** [Silex/docker.el#22]
When I kick `docker-images` locally, the Repository is shown in the way like `docker-registry.mydomain/yu...`. Especially on private registry, the most important part of the repo (the image name) is abbreviated into dots of `...`.

So I thought it would be helpful to make the column widths configurable.

**Comment by Silex** [comment]
@Yuki-Inoue: good idea.

I found this http://stackoverflow.com/questions/28386299/how-to-make-the-package-column-of-emacs-elpa-list-packages-screen-wider

I'll probably write some `tle-make-columns-width-fit-to-content` in https://github.com/Silex/tabulated-list-extensions and use that

**Comment by Silex** [comment]
For a quick hack, modify https://github.com/Silex/docker.el/blob/master/docker-images.el#L209 according to needs.

**Comment by Silex** [comment]
@Yuki-Inoue: you can experiment with https://github.com/Silex/tabulated-list-extensions/tree/automatic-width

`M-x tle-fit-all-columns-to-contents`

**Comment by Silex** [comment]
Alright, please update https://github.com/Silex/tabulated-list-extensions and use `M-x tle-auto-resize-all-columns` for now.

I'll probably make that automatic in the next days for any docker listings.

**Comment by Silex** [comment]
OMG

I just found out about http://melpa.org/#/tablist

**Comment by Yuki-Inoue** [comment]
:-(

**Comment by Silex** [comment]
Well it's also a good news. `tablist` is awesome (filters, marks, etc). It basically implements what I wanted to do since months.

**Comment by gvoysey** [comment]
for anyone else coming here: `>` is the default kbd for `tablist-enlarge-column`, which works with `docker.el` to do exactly what you'd think.
