### ISSUE TITLE
unmatched parenthesis in docker-volume-dired

### ISSUE THREAD

**Issue by LevPetrovitch** [Silex/docker.el#220]
commit https://github.com/Silex/docker.el/commit/39867ab6bcc02b44c01edcfcbd37cd0c055735f7 introduced a mismatching parenthesis (call to s-trim-right non closed). 

Attached a patch 

[docker-patch.txt](https://github.com/Silex/docker.el/files/12395423/docker-patch.txt)

**Comment by Silex** [comment]
Thanks, fixed.
