### ISSUE TITLE
Missing dependency on tablist 1.0 in MELPA Stable

### ISSUE THREAD

**Issue by chrycheng** [Silex/docker.el#225]
Unable to install from MELPA Stable because it depends on tablist 1.0 which is not in MELPA Stable:

```
docker is an incompatible package.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 2.2.0
     Commit: bc11d5e4f21eed57e482116848af1f5c9e21bd3b
    Summary: Interface to Docker
   Requires: aio-1.0, dash-2.19.1, docker-tramp-0.1, emacs-26.1, json-mode-1.8.0, s-1.12.0, tablist-1.0 (not available), transient-0.3.7
   Homepage: https://github.com/Silex/docker.el
   Keywords: filename convenience 

This package allows you to manipulate docker images, containers & more from Emacs.
```

**Comment by Silex** [comment]
Well, I think supporting melpa stable is too complicated.

There is tablist, but there is also transient that cannot be supported because of https://github.com/Silex/docker.el/issues/193.

@purcell pinging you here in case you somehow have a recipe for this situation: packages dependencies that cannot be satisfied in stable.

I never use stable and most people I know don't, so I'm not sure it's worth it to support it.

**Comment by chrycheng** [comment]
Could this be an issue for https://github.com/melpa/melpa and/or https://github.innominds.com/emacsorphanage/tablist instead?  The tablist recipe changed repos in https://github.com/melpa/melpa/commit/6205f77bbb6c3a44146110f2a0e293cdf4280228.  Now, I could be wrong but I think MELPA publishes packages by tags.  The original tablist repo had a 1.0 tag but this new one doesn't.  Could that have caused the dependency to disappear?  Anyway, I also filed https://github.innominds.com/emacsorphanage/tablist/issues/4 but it hasn't gotten any replies yet.

**Comment by Silex** [comment]
@chrycheng: good catch, yes that's why tablist disappeared from melpa stable.

Still my questions about supporting stable remains.

**Comment by chrycheng** [comment]
I understand.  Any new releases published or not published to MELPA stable is entirely up to you.  However, don't you think that one has a responsibility to ensure that any release currently already published to MELPA stable is working?

**Comment by Silex** [comment]
Yes, but what do you think the fix should be? I'm not going to run after tablist to be published on melpa stable.

I'd rather remove support for melpa stable. If you have an idea about how to fix these dependencies issues please share.

**Comment by purcell** [comment]
FWIW I pushed a v1.0 tag for `tablist` (and also made a `v1.1` release with tag), so this should issue should all just clear up now.

**Comment by Silex** [comment]
Thanks @purcell
