### ISSUE TITLE
Docker contexts stopped working

### ISSUE THREAD

**Issue by dinkonin** [Silex/docker.el#228]
I'm using docker contexts to manage multiple docker hosts over ssh, 
After updating to ec748a8605a1204b24f487a8a189be8ffa54befc docker.el does not show any containers or images on the remotre hosts.

Reverting to a29be5804180c571eec09c92b7ed5fddef6eb4e8 fixes it for me.

**Comment by Silex** [comment]
Sorry. Should be fixed now.
