### ISSUE TITLE
when use tramp  sshx, container logs not work as expected, it just open a bash terminal in new window

### ISSUE THREAD

**Issue by zrubing** [Silex/docker.el#231]

**Comment by Silex** [comment]
Sorry forgot about this issue. Will look.

**Comment by Silex** [comment]
Ok, it works if you use:

``` emacs
(setq docker-run-async-with-buffer-function 'docker-run-async-with-buffer-shell)
```

It looks like `vterm-shell` is not respected when starting `vterm-other-window` over TRAMP:

https://github.com/Silex/docker.el/blob/master/docker-process.el#L94-L96

So it's just `/bin/sh` being executed and not the docker command. I guess we can either debug this, or always make it spawn /bin/sh and send the command as keystrokes, but I don't have the resource for this, and many other commands are broken over TRAMP (e.g opening a file inside the container over TRAMP).

**Comment by ghost** [comment]
> It looks like vterm-shell is not respected when starting vterm-other-window over TRAMP:

vterm-shell gets overriden by `(vterm--tramp-get-shell METHOD)` if Tramp is used
https://github.com/akermu/emacs-libvterm/blob/master/vterm.el#L848

I've found a somewhat hacky way - if TRAMP is being used, you need to replace [`vterm-shell`](https://github.com/Silex/docker.el/blob/main/docker-process.el#L96) with `vterm-tramp-shells` and set its value to `'(("ssh" "docker compose ls"))`

This works for me:
```elisp
(defun docker-run-async-with-buffer-vterm-HACK (program &optional interactive &rest args)
      "Execute \"PROGRAM ARGS\" and display output in a new `vterm' buffer."
      (defvar vterm-kill-buffer-on-exit)
      (defvar vterm-tramp-shells)
      (defvar vterm-shell)
      (if (fboundp 'vterm-other-window)
	  (let* ((process-args (-remove 's-blank? (-flatten args)))
		 (vterm-shell (s-join " " (-insert-at 0 program process-args)))
		 (vterm-tramp-shells `(("ssh" ,vterm-shell)))
		 (vterm-kill-buffer-on-exit nil))
            (vterm-other-window
             (apply #'docker-utils-generate-new-buffer-name program process-args)))
	(error "The vterm package is not installed")))


 (setq docker-run-async-with-buffer-function 'docker-run-async-with-buffer-vterm-HACK)
```
