### ISSUE TITLE
Remember the last used global options for docker-compose 

### ISSUE THREAD

**Issue by Velnbur** [Silex/docker.el#232]
I love to play around docker-compose setup using `docker.el` package, but it's kind of frustrating to set parameters `--project-directory` and `--file` each time I want to check out logs or rebuild everything. Sometimes it's even simpler to set an alias for current shell and use it instead.

So it would be great to have and option which will automaticly set last used values of this arguments, and will be reset in some conditions like changing workspace, project and etc.

**Comment by Silex** [comment]
Hello,

https://magit.vc/manual/transient/Saving-Values.html should answer your needs.

Kind regards,
Philippe
