### ISSUE TITLE
Query/Feature Request: running docker images with repeated arguments

### ISSUE THREAD

**Issue by sei-mwd** [Silex/docker.el#233]
I have a docker image that I need to run with multiple volume (`-v`) options.  I don't think that can be currently done with the transient menu, and I have not had success getting it to work using `docker-image-run-custom-args`.  Is there a way to do this that i am missing?  Otherwise, I would like to put in a feature request for this ability.

**Comment by Silex** [comment]
Yes, many people want a similar feature #180, #169 and #137.

Basically the short answer is that transient.el does not support it.

For now you have to use `-v` then type: `FOO -v BAR -v KEWK` (pass the additional -v flags yourself).

pinging @tarsius in case something has changed since
