### ISSUE TITLE
Fix docker-container parsing (by using docker-api.el...?)

### ISSUE THREAD

**Issue by Yuki-Inoue** [Silex/docker.el#24]
Current implementation of docker ps result to `docker-container` conversion is ad-hoc, and easily broken (at least in my local env, in the way I use my docker... ).  This results in, for example, not correct invocation of `C-c d c X` (X is a placeholder).

It would be nice if this conversion is done in a more accurate manner.

Related: #11  (I believe this issue is an instance of such broken conversion)

**Comment by Silex** [comment]
Well yes this is the same report as #11 

I'm closing this, feel free to continue discussing there... I'm not sure I can come up with a decent regexp to parse containers properly, so it's probably time to start spend some time on docker-api.

I believe we can start by using docker-api but only to *get* the various listings. For all the other commands, it's probably better to call "docker" directly.
