### ISSUE TITLE
Recreate `*docker-containers*` buffer on each `docker-containers` invocation

### ISSUE THREAD

**Issue by Yuki-Inoue** [Silex/docker.el#26]
I want the `docker-containers` (or other table list interfaces) to be invoked by considering the current buffer's host. That is, when I'm logging in a server with tramp, and kick the `docker-containers`, it successfully show the list of containers on that logged in host.

Now let's say I wanted to see the containers list on my local host pc.
What I need to do is to
  1. first kill the `*docker-containers*` buffer
  2. and then kick `docker-containers` command on the buffer whose associated file is on my host pc.

Or otherwise I'd still see the containers list of the tramp logged in target pc, even if I kick `docker-containers` on the buffer (which is associated local host's file). I thought just re-creating a buffer wouldn't be so much of a cost, so I thought recreating the buffer on each funciton invocation would solve this problem.

Any opinion?

**Comment by Silex** [comment]
Sounds ok for me... maybe we could add  `default-directory` as part of the buffer name so it always shows the one you expect and it's more verbose. It also allows for multiple container buffers.

If that sounds good, you can use something like I did in https://github.com/tkf/emacs-request/pull/43/commits/6f2515fc827d5fdc9fa77600fea0bf209a696245, the `file-remote-p` part

I will switch to `docker-api` somewhat soonish. I also need to document all the `tablist` improvements (e.g you can resize columns with `<` or `>`, mark/filter by regexp, etc.

**Comment by Yuki-Inoue** [comment]
@Silex it made sense, so I've created an PR which creates separate table buffers for each tramp host. Could you check?
