### ISSUE TITLE
Description, documentation

### ISSUE THREAD

**Issue by vindarel** [Silex/docker.el#3]
It would be great to have at least a brief description of what that package offers ! so than we aren't obliged to read from source.

Screenshots would be nice so than emacs can easily compare to other editors on this page for example: http://domeide.github.io/#emacs (from http://www.reddit.com/r/emacs/comments/3a2epo/docker_meets_the_ide_emacs_help_needed/)

**Comment by Silex** [comment]
@vindarel: sure! but it's *very* alpha at the moment. As soon as I have something semi-working (like images & containers) I'll write a README with examples/screenshots and put it on MELPA.

I hope this is soon :)

**Comment by vindarel** [comment]
Ohoh, I see :) 
Does it serve the project to be reddit'ed so early ?

thx anyway and good luck :)

**Comment by Silex** [comment]
> Does it serve the project to be reddit'ed so early ?

Well yes in the sense that it motivates me to work on it, no in the sense that it's not finished so people might dismiss it.

I'll try to make a somewhat usable release tonight.

**Comment by Silex** [comment]
@vindarel: alright, I improved the documentation quite a lot

Screenshots will follow when things stabilize. I also created issues so you see what's "next".

**Comment by Silex** [comment]
@vindarel: what do you think of the doc now?

**Comment by vindarel** [comment]
Hey, the doc is fantastic ! Very well done, and congrats for the tool. And the guy used it on is page. We're good !

maybe one thing not very clear: do you use magit's pop up system and how ? Allright, we'll see it as soon as we try the package but it may be relevant to show it in the doc.

**Comment by Silex** [comment]
@vindarel: right, the popups needs to be documented too... I can't assume *everyone* is using magit, even tho they should :)

It's basically you press a key, it shows you a popup and you press other keys to do actions.

For example on images, after you select some of them, you can press `D` and it shows a popup offering you to press `D` again to really delete them, and you can also set options like `-f` or `-p` by pressing those.

**Comment by vindarel** [comment]
I myself love it yeah, and I love hydras and discover.el too. A screen or something would make it more appealing but I reckon it isn't really necessary.
