### ISSUE TITLE
Docker-compose support

### ISSUE THREAD

**Issue by mprokopov** [Silex/docker.el#30]
My docker usage pattern is always by docker-compose. 
With version 2 I even do not tag image by myself, it's done automatically. 

So docker-compose support is highly requested :)
I'd be happy to do this by myself, but unfortunately have lack of experience.

**Comment by Silex** [comment]
I am also a heavy user of docker-compose... yes, I'd love docker-compose support :-)

I'll see what I can do, it's very likely to be a bit of a different experience tho.

If you have an UI in mind please share... maybe something around `docker-compose ps` and as actions you have `build`, `up`, etc?

**Comment by mprokopov** [comment]
I see following workflow tasks:
After editing Dockerfile or docker-compose.yml
I'd like to run docker-compose build and docker-compose up next. 
Also while container run I wish to stop, make changes and repeate cycle above. 
Nice feature would be to show running/stopped containers, which mentioned in docker-compose in docker-compose editing buffer. Is it possible to show in current status line?

**Comment by Silex** [comment]
I started some work on it... hope to push something soonish :pray:

**Comment by ksjogo** [comment]
Using compose as well. Happy to help if you push a dev branch.

**Comment by Silex** [comment]
Okay, I started using docker-machine as well as docker-swarm.

I need to stop a bit and think how I am going to support all that. Maybe by splitting in several packages?

Will keep you posted.

**Comment by Silex** [comment]
Hello, please check the `docker-compose` branch.

It's work in progress but it already more or less works for up/stop/rm

**Comment by Silex** [comment]
Continuing in #39
