### ISSUE TITLE
Proposal: use tblui.el

### ISSUE THREAD

**Issue by Yuki-Inoue** [Silex/docker.el#47]
Recently, I realized I was making a lot of similar codes, which define the tabulated list buffer, and then set the magit popups.  I noticed they could be turned into macro, and made this package:

https://github.com/Yuki-Inoue/tblui.el

I think adopting this would clean up the codebase and enable the code concentrate on docker logic.  Any pinion?

**Comment by tzz** [comment]
@Yuki-Inoue that's really nice, I hope you add your macros to the core tabulated-list package!

**Comment by Yuki-Inoue** [comment]
@tzz Unfortunately, I think that's not easy because the package depends on several packages such as `magit-popup`, `dash`, etc, which I believe there are too many contributors and thus there's the FSF license agreement problem...

Making use of it is easy though.  It's available on MELPA so you can try out if you want to.

**Comment by Silex** [comment]
@Yuki-Inoue: that sounds like a good idea... but before that:

@tarsius: I didn't follow magit changes since a while... I kinda remember you planned to do a new popup library which should be better than magit-popup. Is it still the plan? Should we maybe switch to it?

**Comment by tarsius** [comment]
> Is it still the plan?

Yeah... I still plan to do that. It's just that I have focused on improving things that didn't require rethinking old design decision and refactoring core abstractions for a year or so now; and instead did the "easy" things like fixing bugs, improving consistency, and adding new but not very challenging new features. That's about to change now, like in the early days the issue tracker has recently started to collect feature requests where I essentially replied with "Yes I agree, but I cannot/won't do it until after some refactoring".

> Should we maybe switch to it?

It being my successor? No, I haven't written it yet ;-)

Or this? I have some reservations. I might explain that in more detail on `tblui`'s own repository at some point. But basically it boils down to this: I don't think a bit of boilerplate is such a bad thing. Providing a wrapper around the `tabulated-list` api is probably a good idea, but coupling that with `magit-popup` goes too far in my opinion. Convenience macros restrict the possibilities and sometimes that makes them unusable. Many of Magit's own popups do not use `magit-define-popup` for example, when I wrote it, I just didn't and could not anticipate all the needs that would arise later.

**Comment by Silex** [comment]
>> Is it still the plan?

> Yeah... I still plan to do that. It's just that I have focused on improving things that didn't require rethinking old design decision and refactoring core abstractions for a year or so now; and instead did the "easy" things like fixing bugs, improving consistency, and adding new but not very challenging new features. That's about to change now, like in the early days the issue tracker has recently started to collect feature requests where I essentially replied with "Yes I agree, but I cannot/won't do it until after some refactoring".

Alright, no worries take your time :-)
I just needed to know before deciding about tblui... thanks for the detailed answer!

>> Should we maybe switch to it?

> It being my successor? No, I haven't written it yet ;-)

:-)

> Or this? I have some reservations. I might explain that in more detail on tblui's own repository at some point. But basically it boils down to this: I don't think a bit of boilerplate is such a bad thing. Providing a wrapper around the tabulated-list api is probably a good idea, but coupling that with magit-popup goes too far in my opinion. Convenience macros restrict the possibilities and sometimes that makes them unusable. Many of Magit's own popups do not use magit-define-popup for example. When I wrote it, I just didn't and could not anticipate all the needs that would arise later.

Well, I was asking about your successor to magit-popup but since you commented :-) I kinda agree with you that tblui does not fundamentally improve this package implementation... it's more like convenience wrappers that might be removed in the future as implementation changes.

I guess @Yuki-Inoue rationale is that he has another package which is implemented by tabulated-list + magit-popup and he wants to put the common operations between this package and docker.el inside a 3rd package.

@Yuki-Inoue: can you show a little snippet for one of the ressource (maybe containers?) it'd be easier to see what we gain.

**Comment by Silex** [comment]
Sorry I'll close this, while refactoring in https://github.com/Silex/docker.el/commit/94aeafd7fbfb32db262014e694bea8671ec6069e and https://github.com/Silex/docker.el/commit/b3e1bab42f627a5584bc66487e65533f5cc4c075 I discovered if not used carefully using macros actually give you less control, and can obfuscate what is generated. It's not really worth it just to gain one or two lines of code.
