### ISSUE TITLE
Running `docker-containers` fails on Windows

### ISSUE THREAD

**Issue by bleggett** [Silex/docker.el#49]
#### Description

Docker layer: Running `docker-containers` fails on Windows

#### Reproduction guide

- Start Emacs

- Install docker layer

- `M-x docker-containers`

*Observed behaviour:*

`docker-containers-refresh: Symbol’s value as variable is void: docker-containers-show-all`

*Expected behaviour:*

To see a listing of my docker containers

#### System Info
- OS: windows-nt
- Emacs: 25.1.1
- Docker 1.12

**Comment by Silex** [comment]
Good catch! I fixed this in 83ff2c5b2eb8a2b97b3e3a700374fbd2f406a566, can you give it a try?

**Comment by bleggett** [comment]
The commit fixed that error, I now get a `JSON readtable error` when running the command however. Let me know if you need me to do some diagnostics on my end.

**Comment by bleggett** [comment]
So the command it looks like `docker-containers` is trying to run is 

```
docker ps --format=’[{{.ID|json}},{{.Image|json}},{{.Command|json}},{{.RunningFor|json}},{{.Status|json}},{{.Ports|json}},{{.Names|json}}]’ -a 
```

Running that at the command line failed for me until I changed the curved quotes around the format string argument to backticks like so:

```
docker ps --format=`[{{.ID|json}},{{.Image|json}},{{.Command|json}},{{.RunningFor|json}},{{.Status|json}},{{.Ports|json}},{{.Names|json}}]` -a
```

**Comment by Silex** [comment]
windows does not support single quotes?!

**Comment by bleggett** [comment]
Changing line 41 of `docker-container.el` to the following

```
 (data (docker "ps" (format "--format=\"%s\"" fmt) (when docker-containers-show-all "-a ")))
```
fixed it for me, but I don't know if that will work across all platforms.

**Comment by Silex** [comment]
http://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q/357724

Sigh, okay I'll try to use double quotes everywhere.

**Comment by Silex** [comment]
@bleggett: can you test with latest master?

**Comment by bleggett** [comment]
@Silex Looks good to me, thanks! Windows shells are a major pain.

**Comment by Silex** [comment]
:+1:
