### ISSUE TITLE
docker-machine-env fails on Windows

### ISSUE THREAD

**Issue by davidshen84** [Silex/docker.el#50]
`docker-machine-env` fails with message:

    Non-hex digit used for Unicode escape

The cause is the `read` function used in `docker-machine-env-export` expects the `\` in the string to be double-escaped.

**Comment by davidshen84** [comment]
This issue is common on Windows environment. Because Windows uses `\` as the path separator. But if a Linux user uses `\` in the filename, this issue is also present on Linux environment.

**Comment by Silex** [comment]
Alright, we'll follow in #51 then.
