### ISSUE TITLE
Allow to customize the docker command

### ISSUE THREAD

**Issue by pallix** [Silex/docker.el#52]
Hello,

I'm running docker on my system with `sudo docker ...` instead of just `docker`. It would be great if the docker command could be customized.

**Comment by Silex** [comment]
Good idea, I'll see what I can do.

In the meantime, you can modify https://github.com/Silex/docker.el/blob/master/docker-process.el#L31

**Comment by Silex** [comment]
@pallix: #54 was merged, give it a try
