### ISSUE TITLE
Dispatch popups

### ISSUE THREAD

**Issue by jwinder** [Silex/docker.el#53]
I like that this package follows magit in terms of the popups.

I am curious whether others would find more general dispatch popups valuable?

Following magit, a single global keybinding could open a general dispatch popup with shortcuts to all of the current docker-global-mode functions (containers, images, etc). When inside of any of the docker buffers in addition to keybindings for each popup, a general dispatch popup could be used to display shortcuts to the other popups.

For example, a docker-dispatch-popup to display shortcuts for the global functions: docker-containers, docker-images, etc. Inside of the docker-containers buffer, `?` could trigger a docker-containers-popup which displays keybindings for the specific buffer, such as docker-containers-find-file-popup.

**Comment by Silex** [comment]
Oops, seems I missed this issue being created, sorry!

Your idea makes sense, and would replace docker-global-mode which I planned to get rid of anyway.

I'm also considering using https://github.com/abo-abo/hydra instead of the magit popups

**Comment by jwinder** [comment]
Sounds great! I'll go ahead and close this issue then since it sounds like you have some good plans.

**Comment by Silex** [comment]
I'll keep the issue as a reminder :wink:

**Comment by Silex** [comment]
Alright, it's time I work on this. I hope to get something going soonish.

**Comment by jwinder** [comment]
It's working nicely for me! I haven't run into any issues. 💯

**Comment by Silex** [comment]
:+1: nice thanks for testing, will improve a bit then merge.

**Comment by Silex** [comment]
It's merged! :tada:
