### ISSUE TITLE
docker-containers fails on macOS

### ISSUE THREAD

**Issue by benne** [Silex/docker.el#56]
**Description**
On a new install, on macOS, running docker-containers fails with "Unrecognized keyword: template".

**Reproduction**
1. Start emacs
2. Install docker layer through MELPA
3. Add require to init.el as well as (setenv "DOCKER_HOST" "tcp://xxxxxx:2375")
4. M-x docker-containers

_Observed behaviour_
The container list is empty and messages shows:
docker ps --format="[{{.ID|json}},{{.Image|json}},{{.Command|json}},{{.RunningFor|json}},{{.Status|json}},{{.Ports|json}},{{.Names|json}}]" -a
Unrecognized keyword: "template"

Running the command in a clean terminal gives the output:
template: :1:6: executing "" at <json>: wrong number of args for json: want 1 got 0

_Expected behaviour_
The list of containers are shown

_Side note_
Moving the json statement to the front of the field, and removing the pipe, outputs some json, ie. {{json .ID}}

**System info**
macOS Sierra 10.12.1
Emacs 25.1.1
Docker 1.13.0-rc4 (beta)

**Comment by Silex** [comment]
Great but report :+1: 

Well, weird behavior, especially since "template" is not part of the command.

Can you try this command in a terminal:

`docker ps --format="[{{.ID|json}},{{.Image|json}},{{.Command|json}},{{.RunningFor|json}},{{.Status|json}},{{.Ports|json}},{{.Names|json}}]" -a`

If it fails the same way, please try `docker ps -a` and if that does not fail please try docker `1.12.5`, maybe you found a bug in `docker 1.13.0-rc4` ?

**Comment by Silex** [comment]
Ha, the `| json` part looks like it's undocumented, so probably that we rely on an undocumented feature :fearful: 

@Yuki-Inoue: where did you learn about the `| json` for docker format?

**Comment by Silex** [comment]
Looks like `docker ps --format raw` could be used instead.

**Comment by benne** [comment]
I will try the command when I get a chance later today, however, I came across this:
https://docs.docker.com/engine/admin/formatting/

**Comment by Silex** [comment]
Ah! Can you give https://github.com/Silex/docker.el/commit/9da6013f24fb00ffc1f2f15c3aeb05181df5d36f a go and report?

**Comment by benne** [comment]
I'll be home in about six hours - then I'll let you know.

**Comment by benne** [comment]
It works beautifully 👍

**Comment by Silex** [comment]
Merged :wink:

**Comment by tzz** [comment]
> Ha, the | json part looks like it's undocumented, so probably that we rely on an undocumented feature

@Silex the use of `|` in Go templates is standard. See https://golang.org/pkg/text/template/#hdr-Pipelines

I think I suggested the `|` syntax originally, but I agree that it's generally better to use the direct function call syntax, and especially in this case. So it's a nice fix -- thanks for working on it.

**Comment by Silex** [comment]
@tzz: ah, thanks for explaining the `|` syntax :-)

**Comment by anquegi** [comment]
I'm running package docker-20170114.440, I can see machines, images but when I work with containers I get nothing in the buffer and only a message:

`json-read: JSON readtable error
`
complete trace *messages* buffer:

```
docker ps --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .RunningFor}},{{json .Status}},{{json .Ports}},{{json .Names}}]" -a 
*beep*
json-read: JSON readtable error
You can run the command ‚Äòdocker-machines‚Äô with M-x -machines RET
docker images --format="{{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.CreatedSince}}\t{{.Size}}"
You can run the command ‚Äòdocker-images‚Äô with M-x d-im RET
docker images --format="{{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.CreatedSince}}\t{{.Size}}"
*beep*
tablist-next-line: End of buffer
docker ps --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .RunningFor}},{{json .Status}},{{json .Ports}},{{json .Names}}]" -a 
*beep*
json-read: JSON readtable error
docker ps --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .RunningFor}},{{json .Status}},{{json .Ports}},{{json .Names}}]" -a 
*beep*
json-read: JSON readtable error
*beep*
Quit
```
this is my console output:

```
 2017-02-24 12:53:24 ☆ |ruby-2.3.1@learn| Antonios-MBP in ~
○ → docker ps --format="[{{.ID}},{{.Image}},{{.Command}},{{.RunningFor}},{{.Status}},{{.Ports}},{{.Names}}]" -a
[b10d5f24bd66,memcached:latest,"docker-entrypoint.sh",4 hours,Exited (0) 3 hours ago,,memcached-gravity]
[14928c026aba,osixia/openldap:1.1.8,"/container/tool/run",20 hours,Exited (0) 4 hours ago,,ldap-gravity]
[e2a8844d4281,redis:3.0.7,"docker-entrypoint.sh",9 months,Exited (0) 26 hours ago,,redis-antifraude]
[b2194e7f789d,mysql:5.6,"docker-entrypoint.sh",9 months,Exited (0) 26 hours ago,,mysql-antifraud]

Thanks for your help
```

**Comment by Silex** [comment]
@anquegi: hi, what is your docker version?

Also, can you run this in the console and report what it outputs:

```
docker ps --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .RunningFor}},{{json .Status}},{{json .Ports}},{{json .Names}}]" -a
```

**Comment by anquegi** [comment]
@Silex, you where right with your thoughts, I get an error running that command. and also my docker was quite old, 1.10, I updated to the new version from web and now it works:
```

 2017-02-26 08:24:28 ☆ |ruby-2.3.1@learn| Antonios-MBP in ~
○ → docker ps --format="[{{json .ID}},{{json .Image}},{{json .Command}},{{json .RunningFor}},{{json .Status}},{{json .Ports}},{{json .Names}}]" -a
["b10d5f24bd66","memcached:latest","\"docker-entrypoint...\"","47 hours","Exited (0) 47 hours ago","","memcached-gravity"]
["14928c026aba","osixia/openldap:1.1.8","\"/container/tool/run\"","2 days","Exited (255) 10 minutes ago","0.0.0.0:389-\u003e389/tcp, 636/tcp","ldap-gravity"]
["e2a8844d4281","redis:3.0.7","\"docker-entrypoint...\"","9 months","Exited (0) 2 days ago","","redis-antifraude"]
["b2194e7f789d","mysql:5.6","\"docker-entrypoint...\"","9 months","Exited (255) 10 minutes ago","0.0.0.0:3306-\u003e3306/tcp","mysql-antifraud"]

 2017-02-26 08:24:33 ☆ |ruby-2.3.1@learn| Antonios-MBP in ~
○ → docker --version
Docker version 1.13.1, build 092cba3
```

![screen shot 2017-02-26 at 08 26 54](https://cloud.githubusercontent.com/assets/2518346/23337933/8ad07840-fbfd-11e6-8ce2-222b3cc4f0b4.jpg)

Thanks for your help!!

**Comment by Silex** [comment]
Glad it works :+1:
