### ISSUE TITLE
Docker coverage (commands, compose, swarm, etc)

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#6]
# Management commands:

| Items     | Description           | Done  |
|-----------|-----------------------|-------|
| compose   | docker-compose        |       |
| container | Manage containers     | Yes   |
| image     | Manage images         | Yes   |
| machine   | docker-machine        | Yes   |
| network   | Manage networks       | Yes   |
| node      | Manage Swarm nodes    |       |
| plugin    | Manage plugins        |       |
| secret    | Manage Docker secrets |       |
| service   | Manage services       |       |
| stack     | Manage Docker stacks  |       |
| swarm     | Manage Swarm          |       |
| system    | Manage Docker         |       |
| volume    | Manage volumes        | Yes   |

# Other commands:

| Command | Description                                                              | Done |
|---------|--------------------------------------------------------------------------|------|
| attach  | Attach to a running container                                            |      |
| build   | Build an image from a Dockerfile                                         | Yes  |
| commit  | Create a new image from a container's changes                            |      |
| cp      | Copy files/folders between a container and the local filesystem          | Yes  |
| create  | Create a new container                                                   |      |
| diff    | Inspect changes on a container's filesystem                              | Yes  |
| events  | Get real time events from the server                                     |      |
| exec    | Run a command in a running container                                     |      |
| export  | Export a container's filesystem as a tar archive                         |      |
| history | Show the history of an image                                             |      |
| images  | List images                                                              |      |
| import  | Import the contents from a tarball to create a filesystem image          |      |
| info    | Display system-wide information                                          |      |
| inspect | Return low-level information on Docker objects                           | Yes  |
| kill    | Kill one or more running containers                                      | Yes  |
| load    | Load an image from a tar archive or STDIN                                |      |
| login   | Log in to a Docker registry                                              |      |
| logout  | Log out from a Docker registry                                           |      |
| logs    | Fetch the logs of a container                                            | Yes  |
| pause   | Pause all processes within one or more containers                        |      |
| port    | List port mappings or a specific mapping for the container               |      |
| ps      | List containers                                                          |      |
| pull    | Pull an image or a repository from a registry                            |      |
| push    | Push an image or a repository to a registry                              |      |
| rename  | Rename a container                                                       | Yes  |
| restart | Restart one or more containers                                           |      |
| rm      | Remove one or more containers                                            |      |
| rmi     | Remove one or more images                                                |      |
| run     | Run a command in a new container                                         |      |
| save    | Save one or more images to a tar archive (streamed to STDOUT by default) |      |
| search  | Search the Docker Hub for images                                         |      |
| start   | Start one or more stopped containers                                     | Yes  |
| stats   | Display a live stream of container(s) resource usage statistics          |      |
| stop    | Stop one or more running containers                                      |      |
| tag     | Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE                    | Yes  |
| top     | Display the running processes of a container                             |      |
| unpause | Unpause all processes within one or more containers                      | Yes  |
| update  | Update configuration of one or more containers                           |      |
| version | Show the Docker version information                                      |      |
| wait    | Block until one or more containers stop, then print their exit codes     |      |

**Comment by vdemeester** [comment]
@Silex Should we create an issue for some of these, like ``inspect`` (etc…), so it's easier to discuss on each of them (and the way they would be implemented) ?

**Comment by Silex** [comment]
@vdemeester: maybe, but most of these can be implemented fairly straightforward... don't hesitate to create new issues if needed, but this will stay my goto ticket when I have time to implement new stuffs :)

**Comment by vdemeester** [comment]
@Silex ok :wink:

**Comment by Silex** [comment]
@vdemeester: `inspect` is soon to be merged (see the PR)

**Comment by Yuki-Inoue** [comment]
Note that `logs` is implemented in #25 .

**Comment by Silex** [comment]
Ticked ;-)

**Comment by tninja** [comment]
really wish to have commit. Thanks!

**Comment by Silex** [comment]
Alright, I updated the list. I'll refactor it once more to be split in 3 categories:

* Docker basics
  * containers
  * images
  * volumes
  * network
* Docker swarm
  * swarm
  * stack
  * service
* External tools
  * Docker machine
  * Docker compose

Based on this I'll set up some kind of roadmap :-)

**Comment by Silex** [comment]
Closing this as this is too much work to support everything. Will go case by case.
