### ISSUE TITLE
Keybindings unusable in `docker machines` buffer

### ISSUE THREAD

**Issue by spacegoing** [Silex/docker.el#61]
After entered `docker-machines` buffer, all keys like `m` or `O` are unusable.

- OS: darwin 10.12.5
- Emacs: 25.2.1
- Spacemacs: 0.200.9

**Comment by Silex** [comment]
Hum, it works fine by me... can you tell me what `C-h k m` tells you?

**Comment by spacegoing** [comment]
```
m runs the command evil-set-marker (found in
evil-normal-state-map), which is an interactive compiled Lisp
function in ‘evil-common.el’.

It is bound to m.

(evil-set-marker CHAR &optional POS ADVANCE)

Set the marker denoted by CHAR to position POS.
POS defaults to the current position of point.
If ADVANCE is t, the marker advances when inserting text at it;
otherwise, it stays behind.
```
FYI :D

**Comment by spacegoing** [comment]
Btw. I really like this package after few days' usages. The workflow is very smooth. Seems like a porcelain (as `magit` for git) for docker to me:D

**Comment by Silex** [comment]
@spacegoing: ah, so `evil-mode` overwrites `docker-machines-mode` keybindings. I don't know why that does not happen in the other docker buffers tho. Do you know what to do from here? It'd be fairly obvious.

Thanks for the kind words :-) I should really work more on this package! Will try to find some time.

**Comment by spacegoing** [comment]
tks.  No I didn't know what to do. Thanks for your help!

**Comment by Silex** [comment]
I assume the problem is fixed then, reopen the issue if not :wink:
