### ISSUE TITLE
Can't install from MELPA

### ISSUE THREAD

**Issue by schvabodka-man** [Silex/docker.el#63]
Hi there! It seems like there are some troubles with dependencies and json-mode. When i'm attempting to install i'm getting this:
Error: (file-error "http://melpa.org/packages/json-mode-20170418.1900.el" "Not found")

**Comment by Silex** [comment]
Hum, can you test again? I just removed json-mode and docker and reinstalled docker and everything went fine.

If the problem persist, please specify your emacs version and try with `emacs -Q`

**Comment by schvabodka-man** [comment]
Funny how but i still get 
Error: (file-error "http://melpa.org/packages/json-mode-20170418.1900.el" "Not found")
I'm running emacs as emacs-daemon and my emacs version is 25.1.1(Fedora). I'm installing your package with use-package

**Comment by Silex** [comment]
Well I just tried again on a fresh install:

``` bash
docker run -it --rm -e DISPLAY silex/emacs:25.1
```

``` elisp
(require 'package) ;; You might already have this line
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
  (add-to-list 'package-archives (cons "melpa" url) t))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
(package-refresh-contents)
(package-install 'docker)
```

Can you run the same "naked" test?

**Comment by Silex** [comment]
ah! I think you simply forgot to M-x package-refresh-contents

Latest json-mode version is 20170619.1701, yours show 20170418.1900

**Comment by schvabodka-man** [comment]
Thanks! That is the solution, it installed well now. You can close this issue

**Comment by Silex** [comment]
:wink:
