### ISSUE TITLE
Docker shell trying to use system shell

### ISSUE THREAD

**Issue by jethrokuan** [Silex/docker.el#66]
I have my system shell default set to `fish`, but `fish` doesn't exist within the docker container. When I attempt to open a shell via `docker-container-shell`, it complains that the shell does not exist.

Am I doing something wrong? If not, having what shell to run in docker containers being customizable would be amazing!

**Comment by jethrokuan** [comment]
Sorry, by system shell I really meant the one set in emacs, via `explicit-shell-file-name` and `shell-file-name`.

**Comment by Silex** [comment]
Hum, well all we do is call `shell` over a docker-tramp connection... so it makes sense that this is an error.
What could be an idea is to have the shell as an option in the docker shell popup or a `defcustom` to specify the shell, which would be `shell-file-name` by default.

Can you enlighten me about `explicit-shell-file-name`? it's not very clear what it is

**Comment by jethrokuan** [comment]
On further research, I don't think `explicit-shell-file-name` might not be relevant for this case. Here's the docstring for it:

```
"If non-nil, is file name to use for explicitly requested inferior shell.
When nil, such interactive shell sessions fallback to using either
the shell specified in $ESHELL or in `shell-file-name'."
```

And yes, I think a `defcustom` for `docker-shell-file-name` would be great. In `docker-container-shell` one could just check if it is non-nil, and run the shell command within a `let` binding where `shell-file-name` is bound to `docker-shell-file-name`.

**Comment by spiderbit** [comment]
yes run into the same problem in nixos the shell-command defaults to /run/current-system/sw/bin/bash which in the guest docks of course makes no sense.

so I had to set it to /bin/sh why can't it either just default to /bin/sh or checks if the shell-command exist and if not default to /bin/sh?

Or as 2nd best solution do that docker-shell-file-name cause at least you would find that variable faster.

But I think defaulting to /bin/sh as fallback is the better option, cause working without errors out of the box in all/most cases > fix it easily.

**Comment by Silex** [comment]
Should be fixed by 5a6e407ee9c6035245749ee1f249aed16d651728, can you guys test and report?

**Comment by Silex** [comment]
@jethrokuan @spiderbit :wink:

**Comment by jethrokuan** [comment]
Seems to work for me, thanks for the fix!
