### ISSUE TITLE
Adding multiple environment variables to a docker container

### ISSUE THREAD

**Issue by mcraveiro** [Silex/docker.el#68]
Hi Docker.el developers,

Thanks for a great mode, I am now using it as my main way of interfacing with Docker. However, I have a slight problem: I am trying to supply several environment variables to my containers, in a similar approach to what is suggested here [1]. I haven't quite figured out how to do this with Docker.el. I am using the ```Run``` command and the ```-e``` for environment. If I try to put all the variables in one line like so:

```
USER_NAME=$(whoami) USER_ID=$(id -u) GROUP_ID=$(id -g)
```
I get an error:

```
docker: invalid reference format: repository name must be lowercase.
```
Presumably the shell is getting confused because ```-e``` does not support multiple variables; instead one expects multiple ```-e```, one per variable. However, I can't see how to do that from the UI. I also tried quoting:

```
"USER_NAME=$(whoami) USER_ID=$(id -u) GROUP_ID=$(id -g)"
```
The container then starts, but I get this:

```
/ # env | grep USER
USER_NAME=xyz USER_ID=1000 GROUP_ID=1000
```
It seems ```USER_NAME``` was set to the rest of the string. Is there a way to supply multiple environment variables? I also looked for ```--env-file``` but I can't find it.

Thanks in advance.

Marco

[1] https://gist.github.com/renzok/29c9e5744f1dffa392cf

**Comment by mcraveiro** [comment]
Aha, it was actually quite obvious! :-) For anyone with this problem, just add the ```-e```'s to the string itself, like so:

```
USER_NAME=$(whoami) -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)
```
Cheers

**Comment by Silex** [comment]
~Well, until multiple `-e` flags are supported you can do `FOO=123 -e BAR=456`~

Glad you figured it out :+1:
