### ISSUE TITLE
Problems with shell ANSI escape sequences when running Alpine's ash

### ISSUE THREAD

**Issue by mcraveiro** [Silex/docker.el#69]
Hi Docker.el developers,

I don't think this problem is directly related to Docker.el, but maybe you can give me some pointers as to how to solve it. The long and short of it is that when I start an Alpine container using ash, I get some stray escape sequences, even though my ```TERM``` is set to dumb via ```-e```:

```
/ # [6n
/ # [6necho $TERM
echo $TERM
dumb
/ # [6n
```

I've done some google searches but I just can't find a way to stop this. Note that if I run the docker command from a regular emacs shell I also see these stray sequences, which leads me to conclude this is a more general problem.

I've found a few random pages on similar topics, but nothing specific to this:

- [“docker run -dti” with a dumb terminal](https://stackoverflow.com/questions/35690330/docker-run-dti-with-a-dumb-terminal): seems to imply the problem stems from the ```-t``` command.
- [ash man page](https://linux.die.net/man/1/ash): could not spot any thing specific to TERM.
- [Confused about Docker -t option to Allocate a pseudo-TTY](https://stackoverflow.com/questions/30137135/confused-about-docker-t-option-to-allocate-a-pseudo-tty): explains more about ```-t``` but does not quite explain how this links back to the ANSI escape issues.

Any pointers etc are greatly appreciated.

Cheers

Marco

**Comment by mcraveiro** [comment]
It may also be useful to note that if I install bash, the shell works perfectly so this seems to be a ash specific problem.

**Comment by Silex** [comment]
Related to #9 

Well, currently we simply use `async-shell-command`. I think this is the problem https://stackoverflow.com/questions/4726220/how-to-have-colors-in-the-output-of-emacs-shell-command

I'm not sure what the best solution is at the moment, but probably finding a way to reuse `M-x shell` or `M-x ansi-term` would produce better results.

**Comment by mcraveiro** [comment]
Thanks @Silex - I'll stick to bash for now then. Do you want me to close this ticket, given that #9 more or less captures the problem?

**Comment by Silex** [comment]
@mcraveiro: no, #9 is closed because `TERM=dumb` was the workaround. For `sh`/`ash` we need to find something better.

**Comment by mcraveiro** [comment]
OK cool, makes sense. But you know what, I think something is wrong with ash because surely setting ```TERM=dumb``` should stop it from emitting these ANSI escape sequences.

**Comment by Silex** [comment]
This will be fixed by #179

**Comment by Silex** [comment]
It's fixed on master if you have `vterm` installed, otherwise it's still the old behavior.
