### ISSUE TITLE
Have `docker-run` use compilation-mode or some comint variant

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#7]

**Comment by vdemeester** [comment]
:+1: I want(ed) to do that for a while :stuck_out_tongue_closed_eyes:

**Comment by Silex** [comment]
At the moment it uses `async-shell-command`, do you know what would be *right* to use?

I obviously have to work more on the `docker-run` popup to make it more useful (e.g support volumes etc), but the container running works more or less well already (you can run bash for example).

I guess I'd make a mode `docker-run-mode` taht inherits from `comint-mode`?

**Comment by vdemeester** [comment]
> At the moment it uses async-shell-command, do you know what would be right to use?

Not really, I'm not really good in ``emacs-lisp`` for now, I just know enough to do some stuff on my config :sweat_smile:.

> I obviously have to work more on the docker-run popup to make it more useful (e.g support volumes etc), but the container running works more or less well already (you can run bash for example).
> 
> I guess I'd make a mode docker-run-mode that inherits from comint-mode?

I would guess so too. I'll try to get some time to look at this too.

**Comment by Silex** [comment]
This will be fixed by #179
