### ISSUE TITLE
docker in emacs as root

### ISSUE THREAD

**Issue by FrdVnW** [Silex/docker.el#76]
Hello, (more a question than an issue)

I used docker with sudo command on my computer. Is it possible to user this package (docker.el) in emacs with root privilège  in a simple way ?
Two solutions that I want to avoid :
-configure my emacs  in root user ?
-reinstall docker for running as user
thanks

fred

**Comment by Silex** [comment]
Hello,

Use `(setq docker-run-as-root t)` (or `M-x customize-variable docker-run-as-root`)

Also, what most people do is adding their user to the docker group, that way no need for sudo and no need for root.

**Comment by FrdVnW** [comment]
thanks Silex, I see the variable. I tried, but now I have a Tramp sending password that seems to freeze emacs. (I need a killall sudo)

**Comment by Silex** [comment]
> thanks Silex, I see the variable. I tried, but now I have a Tramp sending password that seems to freeze emacs. (I need a killall sudo)

Ah, shame. TRAMP is notoriously hard to debug so this will be complicated to solve. What's the problem with adding yourself to the docker group?

``` shell
sudo usermod -aG docker $USER
```

Then reboot. Then there's no need for sudo.

**Comment by FrdVnW** [comment]
Thanks a lot Silex and for the confirmation about Tramp's complexity ... It works with my $USER in the group docker - kind regards
