### ISSUE TITLE
docker container command for run + shell

### ISSUE THREAD

**Issue by dangirsh** [Silex/docker.el#77]
I often use containers that run tests, then stop. If I try to get a shell into one of these via `b b` in the container view, it only works for running containers. It would be great to have another option for "start + persistent shell" equivalent to `docker run -it <container_name> /bin/bash`.

**Comment by Silex** [comment]
Did you mean `<image_name>` instead of `<container_name>`?

If yes, the run popup is for you, on `docker-images` press `R` and you can change the command with `=c`, but for most image it's already bash so often there's no need to customize.

**Comment by dangirsh** [comment]
Got it, thanks.
