### ISSUE TITLE
docker-logs-mode prints unwanted things

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#79]
@chavezgu 

Your changes introduced this in the logs:

```
-*- mode: docker-logs; default-directory: "~/work/stvs/redmine/" -*-
docker logs started at Tue Apr 17 14:36:24
```

While searching alternatives I fell on `auto-revert-tail-mode` instead of `compilation-mode`. Can you give it a try and report?

**Comment by Silex** [comment]
Wait, docker logs actually has:

```
 -f, --follow[=false]
           Follow log output
```

So it's just a matter of adding this flag in the popup and refactoring a bit.

**Comment by chavezgu** [comment]
Yes. I was thinking the async-shell-mode than compile-mode is probably better suited for this. The -f as flag in the popup sounds great. I can do this.

**Comment by Silex** [comment]
Great, continuing in #80
