### ISSUE TITLE
Lexical Binding

### ISSUE THREAD

**Issue by chavezgu** [Silex/docker.el#81]
Is there any reason why the package is not using "lexical-binding: t" in their files? Apparently is a no brainer: http://nullprogram.com/blog/2016/12/22/

**Comment by Silex** [comment]
No particular reason :-) I agree it could be a good idea to prevent silly mistakes.

**Comment by Silex** [comment]
Fixed by 9cabc8e79fdad86c876a866353c3a10f3bdd181c

**Comment by wyuenho** [comment]
<img width="691" alt="screen shot 2018-05-24 at 06 05 24" src="https://user-images.githubusercontent.com/160028/40465431-839f90a4-5f18-11e8-83ce-e5c07f4d4898.png">

This seems like a good reason not to use lexical binding, but you can fix that easily.

**Comment by Silex** [comment]
Should be fixed by 5535022244834e6256660264dc544258bfa95899
