### ISSUE TITLE
No access to any of the commands

### ISSUE THREAD

**Issue by Grimscythe1983** [Silex/docker.el#82]
The only thing that is available to execute is setting up the global keys. Yet non of the commands are available.

However if I proceed to (let it be) `docker-images.el` file and eval it, then all the images related commands are available. Are we supposed to require each module manually? If yes, then this should be reflected in the documentation.

**Comment by Silex** [comment]
Hum, I guess that means you don't install it through MELPA. When installing through MELPA all the autoloads are done correctly and commands like `M-x docker-images` are available immediatly.

You made me realise that for non-package users just `(require 'docker)` is not enough, indeed one has to include all the sub packages. That is not really optimal, I'll fix it soon.

**Comment by Grimscythe1983** [comment]
I actually have the package installed from MELPA, maybe the recipe is broken?

**Comment by Silex** [comment]
I just tested and removed docker then reinstalled it and everythings works as expected, so I think something is wrong on your side. Can you try removing/reinstalling as well?

**Comment by Grimscythe1983** [comment]
I just did that and everything is working fine now, without any extra `require`s. Thanks for your help!

**Comment by Silex** [comment]
:+1:
