### ISSUE TITLE
Symbol's value as variable is void: docker-arguments

### ISSUE THREAD

**Issue by zakame** [Silex/docker.el#88]
https://github.com/Silex/docker.el/commit/62ce93f029321553ba4f88263aee49be346e2841 introduced docker popup options, but seems to lack `docker-arguments`:

![image](https://user-images.githubusercontent.com/110625/43562680-7d536d1e-9650-11e8-9c03-9e2e5b6bf308.png)

**Comment by Silex** [comment]
Should be fixed by https://github.com/Silex/docker.el/commit/9874e1b4ca117f3c277ec775bd173f1a71bdc21b, sorry for the annoyance.

**Comment by zakame** [comment]
No worries, thanks @Silex ! :+1:
