### ISSUE TITLE
Ability to run two different shells in the same container

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker.el#89]
Hey! First of all, thank you for this amazing package! It's incredibly useful :raised_hands:

An issue I've had with this package is that it doesn't allow me to run two shells in the same container. When I run `docker-containers`, and then press `b` twice to get a shell, it always points me to the already opened shell in that container (if there is one). Is this feasible at all?

**Comment by Silex** [comment]
Hello! Good idea, a88d585e283cb614170e450dd82895612c8d315d should have fixed the problem.
