### ISSUE TITLE
docker run: PS1 bash colors don't display properly

### ISSUE THREAD

**Issue by mikefaille** [Silex/docker.el#9]
This is what I see when I try to have an interactive output.

http://pastebin.com/gtkHBb2n

(github markdown interpret these characters chains ...)

**Comment by Silex** [comment]
Hello,

Those are color escape code... can you explain exactly what you do to trigger this?

For example, if I select the unbutu:latest image and press `R R bash RET` I enter a bash prompt, and `ls -alh --color` works fine...

That said, I agree that the current implementation is to simple. See #7 for what will probably happen in the future.

**Comment by mikefaille** [comment]
Ah, I use https://github.com/bbatsov/solarized-emacs as theme. 

My ubuntu promt : http://pastebin.com/9DNGzUgR

**Comment by Silex** [comment]
I think I found the issue... Please try this:

``` elisp
(ansi-color-for-comint-mode-on)
```

Inside your .emacs file

**Comment by mikefaille** [comment]
It dont work. 
I had (ansi-color-for-comint-mode-on) in my ~/.emacs.d/init.el
Recompile this file. Restart emacs.

And, when I docker exec, it dont work :-/

**Comment by mikefaille** [comment]
If you want a preview : http://postimg.org/image/wfqxnq10p/

**Comment by mikefaille** [comment]
Hum, if I tap enter after broken character, ls show 

```
]0;root@22d820aec226: /root@22d820aec226:/# ls
ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

**Comment by Silex** [comment]
Weird. What is your emacs version?

Can't you try the following steps and report:
* start `emacs -Q` from a terminal
* <kbd>M-x package-initialize</kbd>
* <kbd>M-x docker-images</kbd>
* Mark the ubuntu image using `m`
* Press `R R bash RET`
* Check if it works

Also, I see from your screenshot that sometimes it works sometimes not. Try typing "reset" and "clear" when that happens to see if it repairs it.

**Comment by mikefaille** [comment]
Crap, it work better.

```
]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# 

]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# ls
ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# 

]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# ls
ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# ps aux
ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.0  18172  3328 ?        Ss   18:46   0:00 bash
root        17  0.0  0.0  15572  2164 ?        R+   18:46   0:00 ps aux
]0;root@b4fea5b723d0: /root@b4fea5b723d0:/# 
```

**Comment by Silex** [comment]
Hum, what is your PROMPT? is your shell bash?

**Comment by mikefaille** [comment]
Yes, this is the default bash from ubuntu:latest

**Comment by Silex** [comment]
> Weird. What is your emacs version?

Can you answer this? :)

**Comment by mikefaille** [comment]
Compiled from master : 
GNU Emacs 25.0.50.4 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.2) of 2015-05-03

**Comment by Silex** [comment]
Haha! I was able to reproduce the weirdness!

Basically, only `ubuntu:latest` misbehave... `fedora:latest` or `debian:jessie` behave fine

I'll investiguate.

**Comment by mikefaille** [comment]
Allright ! Do you check centos:7 too ? That was my 1st test.

**Comment by Silex** [comment]
Yep, same problem.

**Comment by Silex** [comment]
Okay... the problem is pretty funny and I'm not sure how to solve it "the right way".

Basically, `PS1` is set like if the terminal had full color support. This is logical because `docker run` emulates a terminal... and then it is displayed inside emacs which doens't have full color support.

The simplest fix right now is to type the following inside the bash session:

``` shell
export PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "
```

**Comment by Silex** [comment]
Other workaround:

``` shell
export TERM=dumb; bash
```

Or from withing docker-run:

`R R sh -c "export TERM=dumb bash"`

**Comment by Silex** [comment]
Ok, simply use the following when running images:

<kbd>R =e TERM=dumb RET R</kbd>

**Comment by mikefaille** [comment]
I'll test it. Thank you !
