### ISSUE TITLE
`docker logs --follow` restart on container restart

### ISSUE THREAD

**Issue by peterbecich** [Silex/docker.el#90]
I get a lot of value out of the `L -f` feature in `docker.el`.  As expected, the Shell that prints the logs goes from `run` to `no process` when the container stops.  Is it feasible to have the Shell process restart when a container with the same name is started?  Thank you

**Comment by Silex** [comment]
Hello! I'm currently on holidays so I can't help much atm, but try a quick Google on "async-shell-command restart process".

I'll look what is feasible or not when I come back.

**Comment by Silex** [comment]
This will be complicated to support. The only thing I found was https://emacs.stackexchange.com/questions/35421/refresh-async-shell-command-buffer?rq=1

Given the current behavior matches the docker one, it does not make sense to bend it to support your use case. What I could recommend is to use `docker-compose logs -f container1 dummycontainer` where dummy-container is just a silly container that never exits, that way whenever container1 restart the logs should restart as well.
