### ISSUE TITLE
Services of docker-compose commands should be selected by actions.

### ISSUE THREAD

**Issue by take-cheeze** [Silex/docker.el#92]
Since setting default values cause conflicts with services option.

As a magit example they have separate action(`magit-fetch-popup`):
https://github.com/magit/magit/blob/aae1e575431ff71dad64f21c39f9db5c61e1527a/lisp/magit-remote.el#L454

**Comment by Silex** [comment]
At first I had it like this, with a completion where you could select:

- All services
- service1
- service2
- ....
- serviceN

But this limited the ability to express this:

`docker-compose restart service1 service4`

Thus I went for the current solution.

Can you provide an example of the conflict with the service option?

As an alternative maybe we could simply `(read-string "Services (ENTER for all)")`.

**Comment by Silex** [comment]
Ah right, but I think it's only visual (e.g things still work as expected).

What do you think about removing services alltogether and just using `read-string` as proposed?

**Comment by take-cheeze** [comment]
It's not only visual. The same options will be passed twice.

**Comment by take-cheeze** [comment]
Well, I would like the path of `all` and specified services to be different.
Most of the time `all` is enough.

**Comment by Silex** [comment]
Can you give https://github.com/Silex/docker.el/tree/docker-compose-services a try?

**Comment by take-cheeze** [comment]
Created what I want to based on your code: #94

**Comment by Silex** [comment]
Following in #94
