### ISSUE TITLE
Down command for docker-compose

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker.el#93]
Hey! First of all, thanks for the addition of `docker-compose` to this package. It's really helpful :raised_hands: I'm now using it as part of my workflow, partifcularly the `docker-compose up` to boot up the current projectile project. However, it seems that there isn't a way to do a `docker-compose down`? Is this by design? How should I do it?

**Comment by Silex** [comment]
Hum, it's just not implemented :-)

I usually simply do `docker-compose rm -vsf`, but maybe I should start using `docker-compose down` :sweat_smile: 

I'll implement it after https://github.com/Silex/docker.el/issues/92 is merged, which will change how you list services

**Comment by Silex** [comment]
Fixed by a1e7aa0e4d9bec8b093d3fec839a50e39315b775
