### ISSUE TITLE
Add `docker attach`?

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker.el#95]
Hey @Silex, once again thank you very much for this package :raised_hands: I'm making it part of my workflow and in this process I'm finding some stuff that would be really cool to have in it.

In this case, I'd really love a way to [attach to a container](https://docs.docker.com/engine/reference/commandline/attach/) from the `docker-containers` list. Usually I do:
```
docker attach <container_id_or_name>
```
to attach to a running container and be able to set breakpoints and so on. Would this be an easy thing to add?

**Comment by Silex** [comment]
Thanks @dcaixinha!

Well attach should not be very complicated, it'd just be `async-shell-command` like we do for docker-run.

I'll see what I can do.

**Comment by Silex** [comment]
Next steps in #97
