### ISSUE TITLE
Add different shells to `docker-containers` list

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker.el#96]
Currently we can get into a container via either `shell` or `eshell`. While I do like them (and mostly try to use `eshell` for everything), there are some cases where I need to use `ansi-term` or `multi-term`. Specifically, I can't set and use breakpoints when programming in [Elixir](https://elixir-lang.org/).

Do you think it'd make sense to have this in `docker.el`?

**Comment by Silex** [comment]
Well `term` does not support TRAMP (which is how we shell in the container). You can use plain `exec` with `bash` to get similar `term` behavior I think, but probably not the full term experience.
